CREATE TABLE `asset_categories` (
	`id` text PRIMARY KEY NOT NULL,
	`organization_id` text NOT NULL,
	`name` text NOT NULL,
	`description` text,
	`depreciation_method` text DEFAULT 'straight_line',
	`useful_life` integer,
	`salvage_value_percent` real DEFAULT 0,
	`created_by` text NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	FOREIGN KEY (`organization_id`) REFERENCES `organizations`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `asset_depreciations` (
	`id` text PRIMARY KEY NOT NULL,
	`organization_id` text NOT NULL,
	`asset_id` text NOT NULL,
	`period_start` integer NOT NULL,
	`period_end` integer NOT NULL,
	`depreciation_amount` real NOT NULL,
	`opening_value` real NOT NULL,
	`closing_value` real NOT NULL,
	`journal_entry_id` text,
	`notes` text,
	`created_by` text,
	`created_at` integer NOT NULL,
	FOREIGN KEY (`organization_id`) REFERENCES `organizations`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`asset_id`) REFERENCES `fixed_assets`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `asset_maintenance` (
	`id` text PRIMARY KEY NOT NULL,
	`organization_id` text NOT NULL,
	`asset_id` text NOT NULL,
	`maintenance_number` text NOT NULL,
	`type` text DEFAULT 'preventive' NOT NULL,
	`status` text DEFAULT 'scheduled' NOT NULL,
	`scheduled_date` integer,
	`completed_date` integer,
	`performed_by` text,
	`vendor` text,
	`description` text,
	`work_performed` text,
	`cost` real DEFAULT 0,
	`downtime` real DEFAULT 0,
	`next_maintenance_date` integer,
	`notes` text,
	`created_by` text NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	FOREIGN KEY (`organization_id`) REFERENCES `organizations`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`asset_id`) REFERENCES `fixed_assets`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `asset_transfers` (
	`id` text PRIMARY KEY NOT NULL,
	`organization_id` text NOT NULL,
	`asset_id` text NOT NULL,
	`transfer_number` text NOT NULL,
	`from_location` text,
	`to_location` text NOT NULL,
	`transfer_date` integer NOT NULL,
	`reason` text,
	`approved_by` text,
	`notes` text,
	`created_by` text NOT NULL,
	`created_at` integer NOT NULL,
	FOREIGN KEY (`organization_id`) REFERENCES `organizations`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`asset_id`) REFERENCES `fixed_assets`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`approved_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `fixed_assets` (
	`id` text PRIMARY KEY NOT NULL,
	`organization_id` text NOT NULL,
	`asset_number` text NOT NULL,
	`category_id` text,
	`name` text NOT NULL,
	`description` text,
	`manufacturer` text,
	`model` text,
	`serial_number` text,
	`location` text,
	`purchase_date` integer,
	`purchase_cost` real NOT NULL,
	`current_value` real NOT NULL,
	`salvage_value` real DEFAULT 0,
	`useful_life` integer,
	`depreciation_method` text DEFAULT 'straight_line',
	`accumulated_depreciation` real DEFAULT 0,
	`status` text DEFAULT 'active' NOT NULL,
	`disposal_date` integer,
	`disposal_value` real,
	`disposal_notes` text,
	`warranty_expiry` integer,
	`notes` text,
	`created_by` text NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	FOREIGN KEY (`organization_id`) REFERENCES `organizations`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`category_id`) REFERENCES `asset_categories`(`id`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
);
