CREATE TABLE `audit_configuration` (
	`id` text PRIMARY KEY NOT NULL,
	`organization_id` text NOT NULL,
	`risk_score_weights` text,
	`risk_thresholds` text,
	`approval_levels` text,
	`default_standards` text,
	`auto_generate_tasks` integer DEFAULT false,
	`auto_generate_threshold` real DEFAULT 70,
	`notification_settings` text,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX `audit_configuration_organization_id_unique` ON `audit_configuration` (`organization_id`);--> statement-breakpoint
CREATE TABLE `audit_findings` (
	`id` text PRIMARY KEY NOT NULL,
	`organization_id` text NOT NULL,
	`audit_task_id` text NOT NULL,
	`finding_number` text NOT NULL,
	`title` text NOT NULL,
	`description` text NOT NULL,
	`severity` text NOT NULL,
	`category` text NOT NULL,
	`evidence` text,
	`attachment_ids` text,
	`corrective_action_required` integer DEFAULT false,
	`corrective_action_description` text,
	`corrective_action_due_date` integer,
	`corrective_action_status` text DEFAULT 'pending',
	`ai_analysis` text,
	`ai_recommendations` text,
	`created_by` text NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE `audit_schedules` (
	`id` text PRIMARY KEY NOT NULL,
	`organization_id` text NOT NULL,
	`name` text NOT NULL,
	`description` text,
	`schedule_type` text NOT NULL,
	`frequency` text NOT NULL,
	`cron_expression` text,
	`configuration` text,
	`notify_users` text,
	`notify_on_completion` integer DEFAULT true,
	`notify_on_high_risk` integer DEFAULT true,
	`high_risk_threshold` real DEFAULT 70,
	`is_active` integer DEFAULT true,
	`last_run_at` integer,
	`last_run_status` text,
	`last_run_result` text,
	`next_run_at` integer,
	`run_count` integer DEFAULT 0,
	`created_by` text NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE `audit_tasks` (
	`id` text PRIMARY KEY NOT NULL,
	`organization_id` text NOT NULL,
	`task_number` text NOT NULL,
	`title` text NOT NULL,
	`description` text,
	`source` text NOT NULL,
	`audit_type` text NOT NULL,
	`priority` text DEFAULT 'medium' NOT NULL,
	`risk_score` real,
	`risk_factors` text,
	`assigned_to` text,
	`assigned_at` integer,
	`status` text DEFAULT 'pending' NOT NULL,
	`due_date` integer,
	`completed_at` integer,
	`entity_type` text,
	`entity_id` text,
	`ai_generated` integer DEFAULT false,
	`ai_confidence` real,
	`ai_reasoning` text,
	`notes` text,
	`attachment_ids` text,
	`created_by` text NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE `commonality_studies` (
	`id` text PRIMARY KEY NOT NULL,
	`organization_id` text NOT NULL,
	`study_number` text NOT NULL,
	`title` text NOT NULL,
	`description` text,
	`study_type` text NOT NULL,
	`analysis_start_date` integer,
	`analysis_end_date` integer,
	`entity_filters` text,
	`react_trace` text,
	`patterns_found` text,
	`recommendations` text,
	`supplier_insights` text,
	`variant_analysis` text,
	`status` text DEFAULT 'draft' NOT NULL,
	`requires_approval` integer DEFAULT true,
	`approval_status` text DEFAULT 'pending',
	`approved_by` text,
	`approved_at` integer,
	`approval_comments` text,
	`created_by` text NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE `compliance_checks` (
	`id` text PRIMARY KEY NOT NULL,
	`organization_id` text NOT NULL,
	`check_number` text NOT NULL,
	`entity_type` text NOT NULL,
	`entity_id` text NOT NULL,
	`standards_checked` text,
	`overall_status` text NOT NULL,
	`compliance_score` real,
	`check_results` text,
	`ai_analysis` text,
	`ai_recommendations` text,
	`requires_action` integer DEFAULT false,
	`action_items` text,
	`performed_by` text NOT NULL,
	`performed_at` integer NOT NULL,
	`created_at` integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE `compliance_conversations` (
	`id` text PRIMARY KEY NOT NULL,
	`organization_id` text NOT NULL,
	`user_id` text NOT NULL,
	`title` text,
	`messages` text NOT NULL,
	`context` text,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE `compliance_knowledge_base` (
	`id` text PRIMARY KEY NOT NULL,
	`organization_id` text NOT NULL,
	`title` text NOT NULL,
	`document_type` text NOT NULL,
	`category` text NOT NULL,
	`subcategory` text,
	`content` text NOT NULL,
	`summary` text,
	`keywords` text,
	`version` text DEFAULT '1.0',
	`effective_date` integer,
	`expiry_date` integer,
	`embedding` blob,
	`source_url` text,
	`last_review_date` integer,
	`reviewed_by` text,
	`status` text DEFAULT 'active' NOT NULL,
	`usage_count` integer DEFAULT 0,
	`created_by` text NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE `improvement_proposals` (
	`id` text PRIMARY KEY NOT NULL,
	`organization_id` text NOT NULL,
	`proposal_number` text NOT NULL,
	`commonality_study_id` text,
	`title` text NOT NULL,
	`description` text NOT NULL,
	`category` text NOT NULL,
	`expected_benefits` text,
	`estimated_cost_saving` real,
	`estimated_quality_improvement` real,
	`implementation_effort` text,
	`priority` text DEFAULT 'medium' NOT NULL,
	`affected_processes` text,
	`affected_suppliers` text,
	`affected_products` text,
	`implementation_steps` text,
	`status` text DEFAULT 'draft' NOT NULL,
	`submitted_at` integer,
	`submitted_by` text,
	`approval_chain` text,
	`current_approval_level` integer DEFAULT 0,
	`implementation_start_date` integer,
	`implementation_end_date` integer,
	`actual_results` text,
	`lessons_learned` text,
	`ai_generated` integer DEFAULT false,
	`created_by` text NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE `risk_assessments` (
	`id` text PRIMARY KEY NOT NULL,
	`organization_id` text NOT NULL,
	`assessment_number` text NOT NULL,
	`assessment_type` text NOT NULL,
	`entity_type` text,
	`entity_id` text,
	`assessment_date` integer NOT NULL,
	`period_start` integer,
	`period_end` integer,
	`overall_risk_score` real NOT NULL,
	`quality_risk_score` real,
	`process_risk_score` real,
	`supplier_risk_score` real,
	`compliance_risk_score` real,
	`risk_factors` text,
	`ai_model_version` text,
	`input_data` text,
	`ai_analysis` text,
	`recommendations` text,
	`suggested_resources` text,
	`tasks_generated` integer DEFAULT 0,
	`status` text DEFAULT 'draft' NOT NULL,
	`created_by` text NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE `risk_data_points` (
	`id` text PRIMARY KEY NOT NULL,
	`organization_id` text NOT NULL,
	`source` text NOT NULL,
	`source_entity_type` text,
	`source_entity_id` text,
	`data_type` text NOT NULL,
	`data_category` text NOT NULL,
	`numeric_value` real,
	`text_value` text,
	`json_value` text,
	`timestamp` integer NOT NULL,
	`metadata` text,
	`embedding` blob,
	`processed` integer DEFAULT false,
	`created_at` integer NOT NULL
);
