CREATE TABLE `dialyse_clinical_alerts` (
	`id` text PRIMARY KEY NOT NULL,
	`organization_id` text NOT NULL,
	`patient_id` text NOT NULL,
	`alert_type` text NOT NULL,
	`severity` text NOT NULL,
	`title` text NOT NULL,
	`description` text,
	`due_date` integer,
	`status` text DEFAULT 'active',
	`assigned_to` text,
	`acknowledged_by` text,
	`acknowledged_at` integer,
	`resolved_by` text,
	`resolved_at` integer,
	`resolution_notes` text,
	`related_to_type` text,
	`related_to_id` text,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	FOREIGN KEY (`organization_id`) REFERENCES `organizations`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`patient_id`) REFERENCES `dialyse_patients`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`assigned_to`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (`acknowledged_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (`resolved_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE set null
);
--> statement-breakpoint
CREATE TABLE `dialyse_patients` (
	`id` text PRIMARY KEY NOT NULL,
	`organization_id` text NOT NULL,
	`contact_id` text NOT NULL,
	`medical_id` text NOT NULL,
	`photo` text,
	`emergency_contact_name` text,
	`emergency_contact_phone` text,
	`emergency_contact_relation` text,
	`blood_type` text,
	`dry_weight` real,
	`renal_failure_etiology` text,
	`medical_history` text,
	`allergies` text,
	`contraindications` text,
	`hiv_status` text DEFAULT 'unknown',
	`hbv_status` text DEFAULT 'unknown',
	`hcv_status` text DEFAULT 'unknown',
	`serology_last_update` integer,
	`requires_isolation` integer DEFAULT false,
	`hepatitis_b_vaccinated` integer DEFAULT false,
	`hepatitis_b_last_dose` integer,
	`patient_status` text DEFAULT 'active',
	`dialysis_start_date` integer,
	`notes` text,
	`created_by` text NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	FOREIGN KEY (`organization_id`) REFERENCES `organizations`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`contact_id`) REFERENCES `contacts`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `dialyse_prescriptions` (
	`id` text PRIMARY KEY NOT NULL,
	`organization_id` text NOT NULL,
	`patient_id` text NOT NULL,
	`prescribed_by` text NOT NULL,
	`prescription_number` text NOT NULL,
	`type` text NOT NULL,
	`is_permanent` integer DEFAULT true,
	`duration_minutes` integer NOT NULL,
	`frequency_per_week` integer NOT NULL,
	`dry_weight` real,
	`blood_flow_rate` integer,
	`dialysate_flow_rate` integer,
	`dialyzer_type` text,
	`membrane_surface` real,
	`anticoagulation_type` text,
	`anticoagulation_dose` text,
	`anticoagulation_protocol` text,
	`session_medications` text,
	`dialysate_type` text,
	`dialysate_sodium` integer,
	`dialysate_potassium` real,
	`dialysate_bicarbonate` integer,
	`dialysate_calcium` real,
	`start_date` integer NOT NULL,
	`end_date` integer,
	`status` text DEFAULT 'active',
	`superseded_by_id` text,
	`notes` text,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	FOREIGN KEY (`organization_id`) REFERENCES `organizations`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`patient_id`) REFERENCES `dialyse_patients`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`prescribed_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `dialyse_machines` (
	`id` text PRIMARY KEY NOT NULL,
	`organization_id` text NOT NULL,
	`warehouse_id` text,
	`machine_number` text NOT NULL,
	`model` text NOT NULL,
	`manufacturer` text,
	`serial_number` text,
	`status` text DEFAULT 'available',
	`isolation_only` integer DEFAULT false,
	`location` text,
	`total_hours` integer DEFAULT 0,
	`total_sessions` integer DEFAULT 0,
	`installation_date` integer,
	`last_maintenance_date` integer,
	`next_maintenance_date` integer,
	`warranty_expiry` integer,
	`notes` text,
	`created_by` text NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	FOREIGN KEY (`organization_id`) REFERENCES `organizations`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`warehouse_id`) REFERENCES `warehouses`(`id`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `dialyse_session_slots` (
	`id` text PRIMARY KEY NOT NULL,
	`organization_id` text NOT NULL,
	`name` text NOT NULL,
	`start_time` text NOT NULL,
	`end_time` text NOT NULL,
	`days_of_week` text NOT NULL,
	`max_patients` integer NOT NULL,
	`active` integer DEFAULT true,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	FOREIGN KEY (`organization_id`) REFERENCES `organizations`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `dialyse_sessions` (
	`id` text PRIMARY KEY NOT NULL,
	`organization_id` text NOT NULL,
	`patient_id` text NOT NULL,
	`prescription_id` text NOT NULL,
	`machine_id` text,
	`slot_id` text,
	`session_number` text NOT NULL,
	`session_date` integer NOT NULL,
	`status` text DEFAULT 'scheduled',
	`scheduled_start_time` text,
	`actual_start_time` integer,
	`actual_end_time` integer,
	`actual_duration_minutes` integer,
	`is_recurring` integer DEFAULT false,
	`recurrence_group_id` text,
	`primary_nurse_id` text,
	`supervising_doctor_id` text,
	`cancellation_reason` text,
	`cancelled_by` text,
	`cancelled_at` integer,
	`notes` text,
	`created_by` text NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	FOREIGN KEY (`organization_id`) REFERENCES `organizations`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`patient_id`) REFERENCES `dialyse_patients`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`prescription_id`) REFERENCES `dialyse_prescriptions`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`machine_id`) REFERENCES `dialyse_machines`(`id`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (`slot_id`) REFERENCES `dialyse_session_slots`(`id`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (`primary_nurse_id`) REFERENCES `employees`(`id`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (`supervising_doctor_id`) REFERENCES `employees`(`id`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (`cancelled_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `dialyse_lab_results` (
	`id` text PRIMARY KEY NOT NULL,
	`organization_id` text NOT NULL,
	`patient_id` text NOT NULL,
	`lab_date` integer NOT NULL,
	`lab_source` text,
	`import_method` text DEFAULT 'manual',
	`urea` real,
	`urea_pre` real,
	`urea_post` real,
	`creatinine` real,
	`kt_v` real,
	`hemoglobin` real,
	`hematocrit` real,
	`pth` real,
	`calcium` real,
	`phosphorus` real,
	`potassium` real,
	`sodium` real,
	`bicarbonate` real,
	`albumin` real,
	`ferritin` real,
	`transferrin_saturation` real,
	`crp` real,
	`all_results` text,
	`has_out_of_range_values` integer DEFAULT false,
	`out_of_range_markers` text,
	`reviewed_by` text,
	`reviewed_at` integer,
	`notes` text,
	`created_by` text NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	FOREIGN KEY (`organization_id`) REFERENCES `organizations`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`patient_id`) REFERENCES `dialyse_patients`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`reviewed_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `dialyse_machine_maintenance` (
	`id` text PRIMARY KEY NOT NULL,
	`organization_id` text NOT NULL,
	`machine_id` text NOT NULL,
	`maintenance_number` text NOT NULL,
	`type` text NOT NULL,
	`status` text DEFAULT 'scheduled',
	`scheduled_date` integer,
	`completed_date` integer,
	`performed_by` text,
	`vendor` text,
	`description` text,
	`work_performed` text,
	`cost` real DEFAULT 0,
	`downtime` integer,
	`parts_replaced` text,
	`notes` text,
	`created_by` text NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	FOREIGN KEY (`organization_id`) REFERENCES `organizations`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`machine_id`) REFERENCES `dialyse_machines`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `dialyse_session_consumables` (
	`id` text PRIMARY KEY NOT NULL,
	`session_id` text NOT NULL,
	`inventory_item_id` text NOT NULL,
	`lot_id` text,
	`quantity` real NOT NULL,
	`unit` text NOT NULL,
	`created_at` integer NOT NULL,
	FOREIGN KEY (`session_id`) REFERENCES `dialyse_sessions`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`inventory_item_id`) REFERENCES `inventory_items`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`lot_id`) REFERENCES `lots`(`id`) ON UPDATE no action ON DELETE set null
);
--> statement-breakpoint
CREATE TABLE `dialyse_session_incidents` (
	`id` text PRIMARY KEY NOT NULL,
	`session_id` text NOT NULL,
	`session_record_id` text,
	`incident_time` integer NOT NULL,
	`type` text NOT NULL,
	`severity` text NOT NULL,
	`description` text,
	`intervention` text,
	`outcome` text,
	`reported_by` text NOT NULL,
	`created_at` integer NOT NULL,
	FOREIGN KEY (`session_id`) REFERENCES `dialyse_sessions`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`session_record_id`) REFERENCES `dialyse_session_records`(`id`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (`reported_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `dialyse_session_medications` (
	`id` text PRIMARY KEY NOT NULL,
	`session_id` text NOT NULL,
	`medication_name` text NOT NULL,
	`dose` text NOT NULL,
	`route` text NOT NULL,
	`administered_at` integer NOT NULL,
	`administered_by` text NOT NULL,
	`lot_id` text,
	`notes` text,
	`created_at` integer NOT NULL,
	FOREIGN KEY (`session_id`) REFERENCES `dialyse_sessions`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`administered_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`lot_id`) REFERENCES `lots`(`id`) ON UPDATE no action ON DELETE set null
);
--> statement-breakpoint
CREATE TABLE `dialyse_session_records` (
	`id` text PRIMARY KEY NOT NULL,
	`session_id` text NOT NULL,
	`phase` text NOT NULL,
	`record_time` integer NOT NULL,
	`weight_kg` real,
	`systolic_bp` integer,
	`diastolic_bp` integer,
	`heart_rate` integer,
	`temperature` real,
	`arterial_pressure` integer,
	`venous_pressure` integer,
	`transmembrane_pressure` integer,
	`blood_flow_rate` integer,
	`dialysate_flow_rate` integer,
	`cumulative_uf` real,
	`clinical_state` text,
	`vascular_access_state` text,
	`compression_time` integer,
	`uf_achieved` real,
	`uf_prescribed` real,
	`has_incident` integer DEFAULT false,
	`recorded_by` text NOT NULL,
	`created_at` integer NOT NULL,
	FOREIGN KEY (`session_id`) REFERENCES `dialyse_sessions`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`recorded_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `dialyse_session_signatures` (
	`id` text PRIMARY KEY NOT NULL,
	`session_id` text NOT NULL,
	`signature_type` text NOT NULL,
	`signed_by` text NOT NULL,
	`signed_at` integer NOT NULL,
	`signature_data` text,
	`created_at` integer NOT NULL,
	FOREIGN KEY (`session_id`) REFERENCES `dialyse_sessions`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`signed_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `dialyse_vascular_accesses` (
	`id` text PRIMARY KEY NOT NULL,
	`organization_id` text NOT NULL,
	`patient_id` text NOT NULL,
	`type` text NOT NULL,
	`location` text NOT NULL,
	`creation_date` integer,
	`surgeon` text,
	`status` text DEFAULT 'active',
	`failure_date` integer,
	`failure_reason` text,
	`removal_date` integer,
	`last_control_date` integer,
	`next_control_date` integer,
	`notes` text,
	`created_by` text NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	FOREIGN KEY (`organization_id`) REFERENCES `organizations`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`patient_id`) REFERENCES `dialyse_patients`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
);
