/**
 * Language Context
 * Provides i18n support for FR, AR, EN
 */

import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'fr' | 'ar' | 'en';

interface Translations {
  [key: string]: string | Translations;
}

// French translations (default)
const fr: Translations = {
  common: {
    save: 'Enregistrer',
    cancel: 'Annuler',
    delete: 'Supprimer',
    edit: 'Modifier',
    add: 'Ajouter',
    create: 'Créer',
    update: 'Mettre à jour',
    search: 'Rechercher',
    filter: 'Filtrer',
    loading: 'Chargement...',
    error: 'Erreur',
    success: 'Succès',
    confirm: 'Confirmer',
    back: 'Retour',
    next: 'Suivant',
    previous: 'Précédent',
    close: 'Fermer',
    yes: 'Oui',
    no: 'Non',
    actions: 'Actions',
    status: 'Statut',
    priority: 'Priorité',
    date: 'Date',
    name: 'Nom',
    email: 'Email',
    phone: 'Téléphone',
    address: 'Adresse',
    description: 'Description',
    amount: 'Montant',
    total: 'Total',
    settings: 'Paramètres',
    language: 'Langue',
    view: 'Voir',
    viewAll: 'Voir tout',
    details: 'Détails',
    export: 'Exporter',
    import: 'Importer',
    refresh: 'Actualiser',
    noData: 'Aucune donnée',
    noResults: 'Aucun résultat',
    all: 'Tous',
    active: 'Actif',
    inactive: 'Inactif',
    pending: 'En attente',
    completed: 'Terminé',
    draft: 'Brouillon',
    new: 'Nouveau',
    code: 'Code',
    type: 'Type',
    currency: 'Devise',
    country: 'Pays',
    timezone: 'Fuseau horaire',
    dateFormat: 'Format de date',
    numberFormat: 'Format numérique',
    required: 'Requis',
    optional: 'Optionnel',
    select: 'Sélectionner',
    submit: 'Soumettre',
    reset: 'Réinitialiser',
    clear: 'Effacer',
    apply: 'Appliquer',
    showing: 'Affichage',
    of: 'sur',
    results: 'résultats',
    page: 'Page',
    perPage: 'par page',
    sortBy: 'Trier par',
    ascending: 'Croissant',
    descending: 'Décroissant',
    notifications: 'Notifications',
    allRightsReserved: 'Tous droits réservés',
    documentation: 'Documentation',
    support: 'Support',
    user: 'Utilisateur',
  },
  auth: {
    login: 'Connexion',
    logout: 'Déconnexion',
    register: 'Inscription',
    email: 'Adresse email',
    password: 'Mot de passe',
    forgotPassword: 'Mot de passe oublié ?',
    rememberMe: 'Se souvenir de moi',
    noAccount: "Vous n'avez pas de compte ?",
    hasAccount: 'Vous avez déjà un compte ?',
    signUp: "S'inscrire",
    signIn: 'Se connecter',
    welcome: 'Bienvenue',
    welcomeBack: 'Bon retour',
    createAccount: 'Créer un compte',
    enterCredentials: 'Entrez vos identifiants pour continuer',
    firstName: 'Prénom',
    lastName: 'Nom',
  },
  profile: {
    title: 'Mon Profil',
    subtitle: 'Gérez vos informations personnelles',
    personalInfo: 'Informations personnelles',
    firstName: 'Prénom',
    lastName: 'Nom',
    email: 'Adresse email',
    avatar: 'Photo de profil',
    avatarUrl: 'URL de la photo',
    changePassword: 'Changer le mot de passe',
    currentPassword: 'Mot de passe actuel',
    newPassword: 'Nouveau mot de passe',
    confirmPassword: 'Confirmer le mot de passe',
    preferences: 'Préférences',
    language: 'Langue',
    theme: 'Thème',
    notifications: 'Notifications',
    updateSuccess: 'Profil mis à jour avec succès',
    updateError: 'Erreur lors de la mise à jour du profil',
    security: 'Sécurité',
    accountSettings: 'Paramètres du compte',
  },
  nav: {
    dashboard: 'Tableau de bord',
    finance: 'Finance',
    crm: 'CRM',
    projects: 'Projets',
    inventory: 'Inventaire',
    hr: 'Ressources Humaines',
    procurement: 'Achats',
    sales: 'Ventes',
    manufacturing: 'Production',
    assets: 'Immobilisations',
    workflows: 'Automatisations',
    integrations: 'Intégrations',
    help: 'Aide',
    settings: 'Paramètres',
    audit: 'Audit Intelligent',
    recipes: 'Recettes',
    traceability: 'Traçabilité',
    payroll: 'Paie',
    ai: 'Intelligence Artificielle',
  },
  sidebar: {
    // Finance
    accounts: 'Comptes',
    invoices: 'Factures',
    payments: 'Paiements',
    reports: 'Rapports',
    // CRM
    companies: 'Entreprises',
    contacts: 'Contacts',
    pipeline: 'Pipeline',
    opportunities: 'Opportunités',
    // Projects
    allProjects: 'Tous les projets',
    tasks: 'Tâches',
    // Inventory
    inventoryItems: 'Articles en stock',
    warehouses: 'Entrepôts',
    movements: 'Mouvements',
    // HR
    employees: 'Employés',
    departments: 'Départements',
    attendance: 'Présence',
    leaves: 'Congés',
    // Procurement
    suppliers: 'Fournisseurs',
    purchaseOrders: 'Commandes achat',
    // Sales
    salesOrders: 'Commandes vente',
    quotations: 'Devis',
    // Manufacturing
    workOrders: 'Ordres de fabrication',
    bom: 'Nomenclatures',
    // Assets
    fixedAssets: 'Immobilisations',
    depreciation: 'Amortissements',
    // Automation
    workflows: 'Flux de travail',
    activityFeed: 'Fil d\'activité',
    apiKeys: 'Clés API',
    webhooks: 'Webhooks',
    // AI
    aiFeatures: 'Fonctionnalités IA',
    aiAssistant: 'Assistant IA',
    // Audit
    auditDashboard: 'Tableau de bord audit',
    auditTasks: 'Tâches d\'audit',
    riskAssessment: 'Évaluation des risques',
    complianceCopilot: 'Copilote conformité',
    commonalityStudy: 'Étude de communalité',
    // Recipes
    recipeCards: 'Fiches recettes',
    ingredients: 'Ingrédients',
    // Traceability
    lotsHaccp: 'Lots & HACCP',
    qualityControl: 'Contrôle qualité',
    // Payroll
    payrollManagement: 'Gestion paie',
    payslips: 'Bulletins de paie',
    // Integrations
    connectors: 'Connecteurs',
    // Settings
    moduleManagement: 'Gestion modules',
    platformSettings: 'Paramètres plateforme',
    // Help
    helpCenter: 'Centre d\'aide',
    gettingStarted: 'Guide démarrage',
    faq: 'FAQ',
    moduleGuides: 'Guides modules',
  },
  dashboard: {
    title: 'Tableau de bord',
    subtitle: 'Vue d\'ensemble de votre activité',
    welcome: 'Bienvenue',
    welcomeBack: 'Bon retour',
    totalRevenue: 'Chiffre d\'affaires total',
    totalExpenses: 'Dépenses totales',
    netProfit: 'Bénéfice net',
    pendingInvoices: 'Factures en attente',
    unpaidInvoices: 'Factures impayées',
    overdue: 'en retard',
    activeCompanies: 'Entreprises actives',
    totalContacts: 'contacts au total',
    openPipeline: 'Pipeline ouvert',
    opportunities: 'opportunités',
    recentActivity: 'Activité récente',
    quickActions: 'Actions rapides',
    newInvoice: 'Nouvelle facture',
    createInvoice: 'Créer une facture',
    addCompany: 'Ajouter une entreprise',
    addContact: 'Ajouter un contact',
    newContact: 'Nouveau contact',
    newOpportunity: 'Nouvelle opportunité',
    newProject: 'Nouveau projet',
    viewReports: 'Voir les rapports',
    salesOverview: 'Aperçu des ventes',
    topCustomers: 'Meilleurs clients',
    recentTransactions: 'Transactions récentes',
    recentInvoices: 'Factures récentes',
    upcomingTasks: 'Tâches à venir',
    cashFlow: 'Flux de trésorerie',
    monthlyStats: 'Statistiques mensuelles',
    dueDate: 'Échéance',
    fromPaidInvoices: 'De {count} factures payées',
    getStarted: 'Démarrer avec Perfex ERP',
    getStartedDescription: 'Commencez par ajouter votre première entreprise ou créer une facture',
  },
  finance: {
    title: 'Finance',
    accounts: 'Plan comptable',
    accountsSubtitle: 'Gérez votre structure comptable',
    allAccounts: 'Tous les comptes',
    assets: 'Actifs',
    liabilities: 'Passifs',
    revenues: 'Produits',
    expenses: 'Charges',
    addAccount: 'Ajouter un compte',
    importFrenchPlan: 'Importer Plan Français',
    importSyscohada: 'Importer SYSCOHADA',
    noAccountsFound: 'Aucun compte trouvé',
    noAccountsDescription: 'Commencez par importer un modèle de plan comptable (Plan Français ou SYSCOHADA) ou créez votre premier compte manuellement.',
    invoices: 'Factures',
    invoicesSubtitle: 'Gérez vos factures clients',
    allInvoices: 'Toutes les factures',
    totalInvoiced: 'Total facturé',
    amountPaid: 'Montant payé',
    amountDue: 'Montant dû',
    searchByInvoiceOrCustomer: 'Rechercher par numéro ou client...',
    createInvoice: 'Créer une facture',
    noInvoicesFound: 'Aucune facture trouvée. Créez votre première facture.',
    payments: 'Paiements',
    paymentsSubtitle: 'Suivez vos encaissements et décaissements',
    reports: 'Rapports financiers',
    reportsSubtitle: 'Analysez vos données financières',
    // Accounts
    accountCode: 'Code compte',
    accountName: 'Nom du compte',
    accountType: 'Type de compte',
    parentAccount: 'Compte parent',
    balance: 'Solde',
    debit: 'Débit',
    credit: 'Crédit',
    asset: 'Actif',
    liability: 'Passif',
    equity: 'Capitaux propres',
    revenue: 'Produits',
    expense: 'Charges',
    // Invoices
    invoiceNumber: 'N° facture',
    customer: 'Client',
    issueDate: 'Date d\'émission',
    dueDate: 'Date d\'échéance',
    subtotal: 'Sous-total',
    tax: 'TVA',
    taxRate: 'Taux TVA',
    discount: 'Remise',
    grandTotal: 'Total TTC',
    paid: 'Payé',
    unpaid: 'Impayé',
    overdue: 'En retard',
    partial: 'Partiel',
    cancelled: 'Annulé',
    sent: 'Envoyé',
    draft: 'Brouillon',
    // Payments
    paymentMethod: 'Mode de paiement',
    paymentDate: 'Date de paiement',
    reference: 'Référence',
    cash: 'Espèces',
    bankTransfer: 'Virement bancaire',
    check: 'Chèque',
    creditCard: 'Carte bancaire',
    other: 'Autre',
    totalPayments: 'Total des paiements',
    count: 'Nombre',
    thisMonth: 'Ce mois',
    average: 'Moyenne',
    recordPayment: 'Enregistrer un paiement',
    searchByReferenceOrNotes: 'Rechercher par référence ou notes...',
    allMethods: 'Toutes les méthodes',
    noPaymentsYet: 'Aucun paiement enregistré',
    startByRecording: 'Commencez par enregistrer votre premier paiement.',
    notes: 'Notes',
    // Reports
    trialBalance: 'Balance générale',
    balanceSheet: 'Bilan',
    incomeStatement: 'Compte de résultat',
    generalLedger: 'Grand livre',
    startDate: 'Date début',
    endDate: 'Date fin',
    asOfDate: 'À la date du',
    generateReport: 'Générer le rapport',
    exportPdf: 'Exporter PDF',
    exportExcel: 'Exporter Excel',
    totalAssets: 'Total actifs',
    totalLiabilities: 'Total passifs',
    totalEquity: 'Total capitaux propres',
    totalRevenue: 'Total produits',
    totalExpenses: 'Total charges',
    netIncome: 'Résultat net',
  },
  crm: {
    title: 'CRM',
    companies: 'Entreprises',
    companiesSubtitle: 'Gérez vos entreprises clients, prospects et partenaires',
    addCompany: 'Ajouter une entreprise',
    searchCompanies: 'Rechercher par nom, email ou téléphone...',
    allTypes: 'Tous les types',
    customer: 'Client',
    prospect: 'Prospect',
    partner: 'Partenaire',
    vendor: 'Fournisseur',
    allStatus: 'Tous les statuts',
    contactInfo: 'Coordonnées',
    size: 'Taille',
    totalCompanies: 'Total entreprises',
    customers: 'Clients',
    prospects: 'Prospects',
    noCompaniesFound: 'Aucune entreprise trouvée',
    noCompaniesDescription: 'Commencez par ajouter votre première entreprise.',
    deleteCompanyConfirm: 'Êtes-vous sûr de vouloir supprimer {name} ? Cette action supprimera également tous les contacts et opportunités associés.',
    contacts: 'Contacts',
    contactsSubtitle: 'Gérez vos contacts clients et prospects',
    addContact: 'Ajouter un contact',
    searchContacts: 'Rechercher par nom, email ou téléphone...',
    allContacts: 'Tous les contacts',
    position: 'Poste',
    primary: 'Principal',
    noCompany: 'Sans entreprise',
    totalContacts: 'Total contacts',
    withCompany: 'Avec entreprise',
    primaryContacts: 'Contacts principaux',
    noContactsFound: 'Aucun contact trouvé',
    noContactsDescription: 'Commencez par ajouter votre premier contact.',
    pipeline: 'Pipeline',
    pipelineSubtitle: 'Suivez vos opportunités commerciales',
    // Companies
    companyName: 'Nom de l\'entreprise',
    industry: 'Secteur d\'activité',
    website: 'Site web',
    employees: 'Employés',
    annualRevenue: 'CA annuel',
    // Contacts
    contactName: 'Nom du contact',
    jobTitle: 'Fonction',
    company: 'Entreprise',
    mobile: 'Mobile',
    // Pipeline
    opportunity: 'Opportunité',
    stage: 'Étape',
    value: 'Valeur',
    probability: 'Probabilité',
    expectedClose: 'Clôture prévue',
    lead: 'Prospect',
    qualified: 'Qualifié',
    proposal: 'Proposition',
    negotiation: 'Négociation',
    won: 'Gagné',
    lost: 'Perdu',
    open: 'Ouvert',
    all: 'Tous',
    totalValue: 'Valeur totale',
    openPipeline: 'Pipeline ouvert',
    deals: 'affaires',
    opportunities: 'opportunités',
    createOpportunity: 'Créer une opportunité',
    noOpportunitiesFound: 'Aucune opportunité trouvée',
    noOpportunitiesDescription: 'Commencez par créer votre première opportunité commerciale.',
    loadingOpportunities: 'Chargement des opportunités...',
  },
  projects: {
    title: 'Projets',
    subtitle: 'Gérez vos projets et tâches',
    projectName: 'Nom du projet',
    projectManager: 'Chef de projet',
    startDate: 'Date début',
    endDate: 'Date fin',
    budget: 'Budget',
    progress: 'Progression',
    notStarted: 'Non démarré',
    inProgress: 'En cours',
    onHold: 'En pause',
    completed: 'Terminé',
    cancelled: 'Annulé',
    tasks: 'Tâches',
    milestones: 'Jalons',
    team: 'Équipe',
    documents: 'Documents',
    newProject: 'Nouveau projet',
    searchProjects: 'Rechercher par nom ou description...',
    allStatus: 'Tous les statuts',
    planning: 'Planification',
    active: 'Actif',
    on_hold: 'En pause',
    allPriorities: 'Toutes les priorités',
    low: 'Basse',
    medium: 'Moyenne',
    high: 'Haute',
    urgent: 'Urgente',
    cost: 'Coût',
    dates: 'Dates',
    start: 'Début',
    due: 'Échéance',
    loadingProjects: 'Chargement des projets...',
    noProjectsFound: 'Aucun projet trouvé',
    noProjectsDescription: 'Commencez par créer votre premier projet.',
    totalProjects: 'Total projets',
    totalBudget: 'Budget total',
  },
  inventory: {
    title: 'Inventaire',
    subtitle: 'Gérez votre stock',
    items: 'Articles',
    itemName: 'Nom de l\'article',
    sku: 'Référence',
    category: 'Catégorie',
    quantity: 'Quantité',
    unitPrice: 'Prix unitaire',
    reorderLevel: 'Seuil de réapprovisionnement',
    warehouse: 'Entrepôt',
    location: 'Emplacement',
    inStock: 'En stock',
    outOfStock: 'Rupture de stock',
    lowStock: 'Stock bas',
    movements: 'Mouvements',
    stockIn: 'Entrée',
    stockOut: 'Sortie',
    transfer: 'Transfert',
    adjustment: 'Ajustement',
    newItem: 'Nouvel article',
    totalItems: 'Total articles',
    activeItems: 'Articles actifs',
    warehouses: 'Entrepôts',
    searchItems: 'Rechercher par SKU, nom ou description...',
    allCategories: 'Toutes les catégories',
    allStatus: 'Tous les statuts',
    loadingItems: 'Chargement des articles...',
    costPrice: 'Prix d\'achat',
    sellingPrice: 'Prix de vente',
    unit: 'Unité',
    noItemsFound: 'Aucun article trouvé',
    noItemsDescription: 'Commencez par ajouter votre premier article.',
  },
  hr: {
    title: 'Ressources Humaines',
    subtitle: 'Gérez vos employés',
    employees: 'Employés',
    employee: 'Employé',
    employeeId: 'Matricule',
    department: 'Département',
    position: 'Poste',
    hireDate: 'Date d\'embauche',
    salary: 'Salaire',
    manager: 'Responsable',
    attendance: 'Présence',
    leaves: 'Congés',
    training: 'Formation',
    performance: 'Performance',
    fullTime: 'Temps plein',
    partTime: 'Temps partiel',
    contractor: 'Contractuel',
    onLeave: 'En congé',
    newEmployee: 'Nouvel employé',
    searchEmployees: 'Rechercher par nom, email ou matricule...',
    allDepartments: 'Tous les départements',
    allTypes: 'Tous les types',
    allStatus: 'Tous les statuts',
    totalEmployees: 'Total employés',
    activeEmployees: 'Employés actifs',
    departments: 'Départements',
    pendingLeave: 'Congés en attente',
    loadingEmployees: 'Chargement des employés...',
    employeeNumber: 'N° Employé',
    type: 'Type',
    noEmployeesFound: 'Aucun employé trouvé',
    noEmployeesDescription: 'Commencez par ajouter votre premier employé. Gérez les informations des employés, suivez les détails d\'emploi et maintenez les dossiers RH efficacement.',
    intern: 'Stagiaire',
    contract: 'CDD',
    full_time: 'Temps plein',
    part_time: 'Temps partiel',
  },
  procurement: {
    title: 'Achats',
    subtitle: 'Gérez vos fournisseurs et commandes',
    suppliers: 'Fournisseurs',
    supplierName: 'Nom du fournisseur',
    purchaseOrders: 'Commandes d\'achat',
    poNumber: 'N° commande',
    orderDate: 'Date commande',
    deliveryDate: 'Date de livraison',
    terms: 'Conditions',
    approved: 'Approuvé',
    received: 'Reçu',
    addSupplier: 'Ajouter un fournisseur',
    searchSuppliers: 'Rechercher des fournisseurs...',
    totalSuppliers: 'Total fournisseurs',
    activeSuppliers: 'Fournisseurs actifs',
    pendingOrders: 'Commandes en attente',
    loadingSuppliers: 'Chargement des fournisseurs...',
    supplierNumber: 'N° Fournisseur',
    rating: 'Évaluation',
    noSuppliersFound: 'Aucun fournisseur trouvé',
    noSuppliersDescription: 'Commencez par ajouter votre premier fournisseur à la base de données.',
  },
  sales: {
    title: 'Ventes',
    subtitle: 'Gérez vos commandes client',
    salesOrders: 'Commandes de vente',
    soNumber: 'N° commande',
    quotations: 'Devis',
    orderDate: 'Date commande',
    shipDate: 'Date d\'expédition',
    shipped: 'Expédié',
    delivered: 'Livré',
    createOrder: 'Créer une commande',
    searchOrders: 'Rechercher des commandes...',
    totalOrders: 'Total commandes',
    draftOrders: 'Commandes brouillon',
    confirmedOrders: 'Commandes confirmées',
    totalRevenue: 'Revenu total',
    loadingOrders: 'Chargement des commandes...',
    orderNumber: 'N° Commande',
    expectedDelivery: 'Livraison prévue',
    subtotal: 'Sous-total',
    tax: 'TVA',
    allStatuses: 'Tous les statuts',
    draft: 'Brouillon',
    confirmed: 'Confirmée',
    processing: 'En cours',
    cancelled: 'Annulée',
    noOrdersFound: 'Aucune commande trouvée',
    noOrdersDescription: 'Commencez par créer votre première commande de vente.',
  },
  manufacturing: {
    title: 'Production',
    subtitle: 'Gérez vos ordres de fabrication',
    workOrders: 'Ordres de fabrication',
    workOrdersSubtitle: 'Gérez les ordres de production et la fabrication',
    woNumber: 'N° OF',
    createWorkOrder: 'Créer un OF',
    searchWorkOrders: 'Rechercher des OF...',
    totalBOMs: 'Total nomenclatures',
    activeBOMs: 'Nomenclatures actives',
    totalWorkOrders: 'Total ordres de fab.',
    inProgress: 'En cours',
    loadingWorkOrders: 'Chargement des OF...',
    scheduledStart: 'Début prévu',
    scheduledEnd: 'Fin prévue',
    qtyPlanned: 'Qté planifiée',
    qtyProduced: 'Qté produite',
    allStatuses: 'Tous les statuts',
    allPriorities: 'Toutes les priorités',
    draft: 'Brouillon',
    released: 'Libéré',
    cancelled: 'Annulé',
    low: 'Basse',
    normal: 'Normale',
    high: 'Haute',
    urgent: 'Urgente',
    noWorkOrdersFound: 'Aucun OF trouvé',
    noWorkOrdersDescription: 'Commencez par créer votre premier ordre de fabrication.',
    product: 'Produit',
    quantity: 'Quantité',
    scheduledDate: 'Date planifiée',
    completedDate: 'Date de fin',
    bom: 'Nomenclature',
    routing: 'Gamme',
    planned: 'Planifié',
    inProduction: 'En production',
    qualityCheck: 'Contrôle qualité',
  },
  assets: {
    title: 'Immobilisations',
    subtitle: 'Gérez vos actifs fixes',
    fixedAssets: 'Immobilisations',
    assetName: 'Nom de l\'actif',
    assetCode: 'Code',
    purchaseDate: 'Date d\'acquisition',
    purchaseValue: 'Valeur d\'acquisition',
    currentValue: 'Valeur actuelle',
    depreciation: 'Amortissement',
    depreciationMethod: 'Méthode d\'amortissement',
    usefulLife: 'Durée d\'utilisation',
    salvageValue: 'Valeur résiduelle',
    linear: 'Linéaire',
    declining: 'Dégressif',
    addAsset: 'Ajouter un actif',
    searchAssets: 'Rechercher des actifs...',
    totalAssets: 'Total actifs',
    activeAssets: 'Actifs actifs',
    totalValue: 'Valeur totale',
    pendingMaintenance: 'Maintenance en attente',
    loadingAssets: 'Chargement des actifs...',
    assetNumber: 'N° Actif',
    location: 'Emplacement',
    purchaseCost: 'Coût d\'achat',
    allStatuses: 'Tous les statuts',
    active: 'Actif',
    disposed: 'Cédé',
    sold: 'Vendu',
    donated: 'Donné',
    lost: 'Perdu',
    noAssetsFound: 'Aucun actif trouvé',
    noAssetsDescription: 'Commencez par ajouter votre premier actif fixe.',
  },
  workflows: {
    title: 'Automatisation des Workflows',
    subtitle: 'Gérez les workflows, approbations, webhooks et intégrations',
    workflows: 'Flux de travail',
    workflowName: 'Nom du flux',
    trigger: 'Déclencheur',
    actions: 'Actions',
    conditions: 'Conditions',
    enabled: 'Activé',
    disabled: 'Désactivé',
    apiKeys: 'Clés API',
    webhooks: 'Webhooks',
    activityFeed: 'Fil d\'activité',
    createApiKey: 'Créer une clé API',
    createWebhook: 'Créer un webhook',
    createWorkflow: 'Créer un workflow',
    totalWorkflows: 'Total Workflows',
    activeWorkflows: 'actif(s)',
    pendingApprovals: 'Approbations en attente',
    ofTotal: 'sur',
    total: 'total',
    activeWebhooks: 'Webhooks actifs',
    tags: 'Tags',
    approvals: 'Approbations',
    searchWorkflows: 'Rechercher des workflows...',
    allEntityTypes: 'Tous les types d\'entités',
    invoice: 'Facture',
    purchaseOrder: 'Bon de commande',
    expense: 'Dépense',
    opportunity: 'Opportunité',
    loadingWorkflows: 'Chargement des workflows...',
    entityType: 'Type d\'entité',
    priority: 'Priorité',
    created: 'Créé',
    active: 'Actif',
    inactive: 'Inactif',
    noWorkflowsFound: 'Aucun workflow trouvé',
    noWorkflowsDescription: 'Créez votre premier workflow pour automatiser vos processus métier',
    searchWebhooks: 'Rechercher des webhooks...',
    loadingWebhooks: 'Chargement des webhooks...',
    url: 'URL',
    events: 'Événements',
    event: 'événement',
    lastTriggered: 'Dernier déclenchement',
    never: 'Jamais',
    noWebhooksFound: 'Aucun webhook trouvé',
    noWebhooksDescription: 'Créez votre premier webhook pour recevoir des notifications d\'événements',
    searchApiKeys: 'Rechercher des clés API...',
    loadingApiKeys: 'Chargement des clés API...',
    permissions: 'Permissions',
    permission: 'permission',
    rateLimit: 'Limite de taux',
    perHour: '/heure',
    expires: 'Expire',
    lastUsed: 'Dernière utilisation',
    noApiKeysFound: 'Aucune clé API trouvée',
    noApiKeysDescription: 'Créez votre première clé API pour un accès programmatique',
    approvalsComingSoon: 'Gestion des approbations bientôt disponible',
    tagsComingSoon: 'Gestion des tags bientôt disponible',
  },
  integrations: {
    title: 'Intégrations',
    subtitle: 'Connectez vos services externes',
    connectors: 'Connecteurs',
    connected: 'Connecté',
    disconnected: 'Déconnecté',
    configure: 'Configurer',
    tunisian: 'Intégrations Tunisie',
    apiConfig: 'Configuration API',
  },
  audit: {
    title: 'Audit Intelligent',
    subtitle: 'Audit et conformité assistés par IA',
    dashboard: 'Tableau de bord',
    tasks: 'Tâches d\'audit',
    riskAssessment: 'Évaluation des risques',
    complianceCopilot: 'Copilote conformité',
    commonalityStudy: 'Étude de communalité',
    riskScore: 'Score de risque',
    compliance: 'Conformité',
    findings: 'Constats',
    recommendations: 'Recommandations',
    critical: 'Critique',
    high: 'Élevé',
    medium: 'Moyen',
    low: 'Faible',
    // Dashboard
    smartAuditSystem: 'Smart Audit System',
    smartAuditSubtitle: 'Système d\'audit intelligent propulsé par l\'IA',
    auditTasks: 'Tâches d\'Audit',
    pending: 'en attente',
    averageRiskScore: 'Score de Risque Moyen',
    highRiskEntities: 'entités à haut risque',
    complianceRate: 'Taux de Conformité',
    isoStandards: 'ISO 9001 & standards',
    proposalsInProgress: 'Propositions en Cours',
    generatedByAI: 'générées par IA',
    newTask: 'Nouvelle Tâche',
    last7days: '7 derniers jours',
    last30days: '30 derniers jours',
    last90days: '90 derniers jours',
    // Modules
    ef1Title: 'EF1: Évaluation des Risques',
    ef1Description: 'Modèle dynamique d\'évaluation des risques qualité avec analyse IA',
    ef1Feature1: 'Analyse NLP des données',
    ef1Feature2: 'Score de risque 0-100',
    ef1Feature3: 'Génération auto de tâches',
    ef2Title: 'EF2: Copilote Conformité',
    ef2Description: 'Assistant IA pour la conformité manufacturière (ISO 9001, OSHA)',
    ef2Feature1: 'Chat avec base de connaissances',
    ef2Feature2: 'Vérification de conformité',
    ef2Feature3: 'Insights exploitables',
    ef3Title: 'EF3: Analyse des Points Communs',
    ef3Description: 'Agent ReAct pour l\'analyse des patterns et recommandations',
    ef3Feature1: 'Framework ReAct',
    ef3Feature2: 'Analyse des variantes',
    ef3Feature3: 'Propositions d\'amélioration',
    recentTasks: 'Tâches Récentes',
    viewAll: 'Voir tout',
    noRecentTasks: 'Aucune tâche récente',
    createFirstTask: 'Créer une première tâche',
    aiInsights: 'Insights IA',
    noInsightsAvailable: 'Aucun insight disponible',
    launchRiskAssessment: 'Lancez une évaluation de risque pour générer des insights',
    riskMap: 'Carte des Risques',
    quality: 'Qualité',
    process: 'Processus',
    suppliers: 'Fournisseurs',
    riskScoreLabel: 'Score de risque',
    // Tasks page
    tasksTitle: 'Tâches d\'Audit',
    tasksSubtitle: 'Gérez et suivez vos tâches d\'audit qualité',
    searchTask: 'Rechercher une tâche...',
    allStatuses: 'Tous les statuts',
    inProgress: 'En cours',
    completed: 'Terminé',
    cancelled: 'Annulé',
    allTypes: 'Tous les types',
    qualityType: 'Qualité',
    processType: 'Processus',
    supplierType: 'Fournisseur',
    safetyType: 'Sécurité',
    complianceType: 'Conformité',
    noAuditTasks: 'Aucune tâche d\'audit',
    noAuditTasksDescription: 'Créez votre première tâche d\'audit ou lancez une évaluation de risque.',
    aiAssessment: 'Évaluation IA',
    task: 'Tâche',
    type: 'Type',
    priority: 'Priorité',
    risk: 'Risque',
    dueDate: 'Date limite',
    aiGenerated: 'Générée par IA',
    previous: 'Précédent',
    next: 'Suivant',
    pageOf: 'Page {page} sur {total}',
    // Risk Assessment page (EF1)
    ef1DynamicRiskTitle: 'EF1: Évaluation Dynamique des Risques',
    ef1DynamicRiskSubtitle: 'Analyse IA des risques qualité avec génération automatique de tâches',
    workOrder: 'Ordre de Fabrication',
    supplier: 'Fournisseur',
    product: 'Produit',
    facility: 'Installation',
    analysisInProgress: 'Analyse en cours...',
    launchAssessment: 'Lancer l\'évaluation',
    latestAssessment: 'Dernière Évaluation',
    overallScore: 'Score Global',
    generateTasks: 'Générer Tâches',
    identifiedRiskFactors: 'Facteurs de Risque Identifiés',
    noSpecificRiskFactors: 'Aucun facteur de risque spécifique identifié',
    aiRecommendations: 'Recommandations IA',
    noRecommendations: 'Aucune recommandation disponible',
    assessmentHistory: 'Historique des Évaluations',
    number: 'Numéro',
    score: 'Score',
    tasksLabel: 'Tâches',
    generated: 'générées',
    noAssessments: 'Aucune évaluation de risque. Lancez votre première analyse.',
    // Compliance Copilot page (EF2)
    ef2CopilotTitle: 'EF2: Copilote de Conformité',
    ef2CopilotSubtitle: 'Assistant IA pour la conformité ISO 9001, OSHA et standards internes',
    chat: 'Chat',
    knowledgeBase: 'Base de Connaissances',
    welcomeToCopilot: 'Bienvenue dans le Copilote de Conformité',
    copilotDescription: 'Posez vos questions sur les standards ISO 9001, ISO 14001, OSHA, ou les procédures internes de qualité.',
    suggestion1: 'Quelles sont les exigences ISO 9001 pour la documentation?',
    suggestion2: 'Comment gérer une non-conformité majeure?',
    suggestion3: 'Procédure d\'audit interne',
    sources: 'Sources',
    askQuestion: 'Posez votre question sur la conformité...',
    searchKnowledgeBase: 'Rechercher dans la base de connaissances...',
    add: 'Ajouter',
    emptyKnowledgeBase: 'Base de connaissances vide',
    addStandardsProcedures: 'Ajoutez des standards, procédures et guides de conformité.',
    consultations: 'consultations',
    // Commonality Study page (EF3)
    ef3Subtitle: 'Agent ReAct pour l\'identification de patterns et recommandations d\'amélioration',
    newStudy: 'Nouvelle Étude',
    studyTitle: 'Titre de l\'étude (optionnel)',
    defectAnalysis: 'Analyse des Défauts',
    supplierComparison: 'Comparaison Fournisseurs',
    processImprovement: 'Amélioration Processus',
    rootCauseAnalysis: 'Analyse Cause Racine',
    reactAnalysisInProgress: 'Analyse ReAct en cours...',
    launchAnalysis: 'Lancer l\'analyse',
    commonalityStudies: 'Études de Points Communs',
    study: 'Étude',
    patterns: 'Patterns',
    identified: 'identifiés',
    approval: 'Approbation',
    viewDetails: 'Voir détails',
    approve: 'Approuver',
    reject: 'Rejeter',
    noStudies: 'Aucune étude. Lancez votre première analyse ReAct.',
    reactTrace: 'Trace ReAct',
    step: 'Étape',
    thought: 'Pensée',
    action: 'Action',
    observation: 'Observation',
    patternsIdentified: 'Patterns Identifiés',
    frequency: 'Fréquence',
    confidence: 'Confiance',
    supplierInsights: 'Insights Fournisseurs',
    issues: 'Problèmes',
  },
  recipes: {
    title: 'Recettes',
    subtitle: 'Gérez vos recettes, formulations et fiches techniques',
    recipeCards: 'Fiches recettes',
    recipeName: 'Nom de la recette',
    ingredients: 'Ingrédients',
    instructions: 'Instructions',
    yield: 'Rendement',
    servings: 'Portions',
    prepTime: 'Temps de préparation',
    cookTime: 'Temps de cuisson',
    totalTime: 'Temps total',
    costPerServing: 'Coût par portion',
    nutritionalInfo: 'Informations nutritionnelles',
    allergens: 'Allergènes',
    newRecipe: 'Nouvelle Recette',
    totalRecipes: 'Total Recettes',
    activeRecipes: 'Actives',
    draftRecipes: 'Brouillons',
    categories: 'Catégories',
    searchRecipe: 'Rechercher une recette...',
    allStatuses: 'Tous les statuts',
    allCategories: 'Toutes les catégories',
    active: 'Active',
    draft: 'Brouillon',
    archived: 'Archivée',
    sellingPrice: 'Prix de vente',
    view: 'Voir',
    noRecipes: 'Aucune recette',
    noRecipesDescription: 'Commencez par créer votre première recette.',
    createRecipe: 'Créer une recette',
    deleteRecipe: 'Supprimer la recette',
    deleteConfirmation: 'Êtes-vous sûr de vouloir supprimer',
    deleteWarning: 'Cette action est irréversible.',
    deleting: 'Suppression...',
  },
  traceability: {
    title: 'Traçabilité',
    subtitle: 'Lots et conformité HACCP',
    lots: 'Lots',
    lotNumber: 'N° de lot',
    batchNumber: 'N° de batch',
    productionDate: 'Date de production',
    expiryDate: 'Date d\'expiration',
    haccp: 'HACCP',
    ccp: 'Points critiques',
    monitoring: 'Surveillance',
    corrective: 'Actions correctives',
    verification: 'Vérification',
    temperature: 'Température',
    humidity: 'Humidité',
  },
  payroll: {
    title: 'Gestion de la Paie',
    subtitle: 'Gérez les salaires et bulletins de paie',
    periods: 'Périodes de paie',
    payslips: 'Bulletins de paie',
    employees: 'Employés',
    grossSalary: 'Salaire brut',
    netSalary: 'Salaire net',
    deductions: 'Retenues',
    contributions: 'Cotisations',
    bonuses: 'Primes',
    overtime: 'Heures supplémentaires',
    taxes: 'Impôts',
    cnss: 'CNSS',
    periodMonth: 'Mois',
    periodYear: 'Année',
    generate: 'Générer',
    validate: 'Valider',
    process: 'Traiter',
  },
  settings: {
    title: 'Paramètres',
    subtitle: 'Configurez votre plateforme',
    platform: 'Paramètres plateforme',
    modules: 'Gestion des modules',
    language: 'Langue de la plateforme',
    country: 'Pays',
    currency: 'Devise par défaut',
    timezone: 'Fuseau horaire',
    dateFormat: 'Format de date',
    numberFormat: 'Format numérique',
    theme: 'Thème',
    darkMode: 'Mode sombre',
    lightMode: 'Mode clair',
    system: 'Système',
    security: 'Sécurité',
    backup: 'Sauvegarde',
    import: 'Import de données',
    export: 'Export de données',
    users: 'Utilisateurs',
    roles: 'Rôles',
    permissions: 'Permissions',
    organization: 'Organisation',
    companyInfo: 'Informations entreprise',
    billing: 'Facturation',
    subscription: 'Abonnement',
    modulesList: 'Liste des modules',
    enableModule: 'Activer le module',
    disableModule: 'Désactiver le module',
  },
  help: {
    title: 'Centre d\'Aide',
    subtitle: 'Documentation et support',
    gettingStarted: 'Guide de démarrage',
    faq: 'Questions fréquentes',
    moduleGuides: 'Guides des modules',
    searchHelp: 'Rechercher dans l\'aide',
    contactSupport: 'Contacter le support',
    documentation: 'Documentation',
    tutorials: 'Tutoriels',
    videos: 'Vidéos',
    community: 'Communauté',
  },
  ai: {
    title: 'Intelligence Artificielle',
    subtitle: 'Fonctionnalités IA avancées',
    assistant: 'Assistant IA',
    predictions: 'Prédictions',
    insights: 'Analyses',
    automation: 'Automatisation',
    askAnything: 'Posez votre question...',
    generating: 'Génération en cours...',
    suggestions: 'Suggestions',
  },
  languages: {
    fr: 'Français',
    en: 'English',
    ar: 'العربية',
  },
  footer: {
    allRightsReserved: 'Tous droits réservés',
    documentation: 'Documentation',
    support: 'Support',
  },
};

// English translations
const en: Translations = {
  common: {
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    create: 'Create',
    update: 'Update',
    search: 'Search',
    filter: 'Filter',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    confirm: 'Confirm',
    back: 'Back',
    next: 'Next',
    previous: 'Previous',
    close: 'Close',
    yes: 'Yes',
    no: 'No',
    actions: 'Actions',
    status: 'Status',
    priority: 'Priority',
    date: 'Date',
    name: 'Name',
    email: 'Email',
    phone: 'Phone',
    address: 'Address',
    description: 'Description',
    amount: 'Amount',
    total: 'Total',
    settings: 'Settings',
    language: 'Language',
    view: 'View',
    viewAll: 'View All',
    details: 'Details',
    export: 'Export',
    import: 'Import',
    refresh: 'Refresh',
    noData: 'No data',
    noResults: 'No results',
    all: 'All',
    active: 'Active',
    inactive: 'Inactive',
    pending: 'Pending',
    completed: 'Completed',
    draft: 'Draft',
    new: 'New',
    code: 'Code',
    type: 'Type',
    currency: 'Currency',
    country: 'Country',
    timezone: 'Timezone',
    dateFormat: 'Date Format',
    numberFormat: 'Number Format',
    required: 'Required',
    optional: 'Optional',
    select: 'Select',
    submit: 'Submit',
    reset: 'Reset',
    clear: 'Clear',
    apply: 'Apply',
    showing: 'Showing',
    of: 'of',
    results: 'results',
    page: 'Page',
    perPage: 'per page',
    sortBy: 'Sort by',
    ascending: 'Ascending',
    descending: 'Descending',
    notifications: 'Notifications',
    allRightsReserved: 'All rights reserved',
    documentation: 'Documentation',
    support: 'Support',
    user: 'User',
  },
  auth: {
    login: 'Login',
    logout: 'Logout',
    register: 'Register',
    email: 'Email address',
    password: 'Password',
    forgotPassword: 'Forgot password?',
    rememberMe: 'Remember me',
    noAccount: "Don't have an account?",
    hasAccount: 'Already have an account?',
    signUp: 'Sign up',
    signIn: 'Sign in',
    welcome: 'Welcome',
    welcomeBack: 'Welcome back',
    createAccount: 'Create account',
    enterCredentials: 'Enter your credentials to continue',
    firstName: 'First name',
    lastName: 'Last name',
  },
  profile: {
    title: 'My Profile',
    subtitle: 'Manage your personal information',
    personalInfo: 'Personal Information',
    firstName: 'First Name',
    lastName: 'Last Name',
    email: 'Email Address',
    avatar: 'Profile Picture',
    avatarUrl: 'Picture URL',
    changePassword: 'Change Password',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmPassword: 'Confirm Password',
    preferences: 'Preferences',
    language: 'Language',
    theme: 'Theme',
    notifications: 'Notifications',
    updateSuccess: 'Profile updated successfully',
    updateError: 'Error updating profile',
    security: 'Security',
    accountSettings: 'Account Settings',
  },
  nav: {
    dashboard: 'Dashboard',
    finance: 'Finance',
    crm: 'CRM',
    projects: 'Projects',
    inventory: 'Inventory',
    hr: 'Human Resources',
    procurement: 'Procurement',
    sales: 'Sales',
    manufacturing: 'Manufacturing',
    assets: 'Assets',
    workflows: 'Workflows',
    integrations: 'Integrations',
    help: 'Help',
    settings: 'Settings',
    audit: 'Smart Audit',
    recipes: 'Recipes',
    traceability: 'Traceability',
    payroll: 'Payroll',
    ai: 'Artificial Intelligence',
  },
  sidebar: {
    accounts: 'Accounts',
    invoices: 'Invoices',
    payments: 'Payments',
    reports: 'Reports',
    companies: 'Companies',
    contacts: 'Contacts',
    pipeline: 'Pipeline',
    opportunities: 'Opportunities',
    allProjects: 'All Projects',
    tasks: 'Tasks',
    inventoryItems: 'Inventory Items',
    warehouses: 'Warehouses',
    movements: 'Movements',
    employees: 'Employees',
    departments: 'Departments',
    attendance: 'Attendance',
    leaves: 'Leaves',
    suppliers: 'Suppliers',
    purchaseOrders: 'Purchase Orders',
    salesOrders: 'Sales Orders',
    quotations: 'Quotations',
    workOrders: 'Work Orders',
    bom: 'Bill of Materials',
    fixedAssets: 'Fixed Assets',
    depreciation: 'Depreciation',
    workflows: 'Workflows',
    activityFeed: 'Activity Feed',
    apiKeys: 'API Keys',
    webhooks: 'Webhooks',
    aiFeatures: 'AI Features',
    aiAssistant: 'AI Assistant',
    auditDashboard: 'Audit Dashboard',
    auditTasks: 'Audit Tasks',
    riskAssessment: 'Risk Assessment',
    complianceCopilot: 'Compliance Copilot',
    commonalityStudy: 'Commonality Study',
    recipeCards: 'Recipe Cards',
    ingredients: 'Ingredients',
    lotsHaccp: 'Lots & HACCP',
    qualityControl: 'Quality Control',
    payrollManagement: 'Payroll Management',
    payslips: 'Payslips',
    connectors: 'Connectors',
    moduleManagement: 'Module Management',
    platformSettings: 'Platform Settings',
    helpCenter: 'Help Center',
    gettingStarted: 'Getting Started',
    faq: 'FAQ',
    moduleGuides: 'Module Guides',
  },
  dashboard: {
    title: 'Dashboard',
    subtitle: 'Overview of your activity',
    welcome: 'Welcome',
    welcomeBack: 'Welcome back',
    totalRevenue: 'Total Revenue',
    totalExpenses: 'Total Expenses',
    netProfit: 'Net Profit',
    pendingInvoices: 'Pending Invoices',
    unpaidInvoices: 'Unpaid Invoices',
    overdue: 'overdue',
    activeCompanies: 'Active Companies',
    totalContacts: 'total contacts',
    openPipeline: 'Open Pipeline',
    opportunities: 'opportunities',
    recentActivity: 'Recent Activity',
    quickActions: 'Quick Actions',
    newInvoice: 'New Invoice',
    createInvoice: 'Create Invoice',
    addCompany: 'Add Company',
    addContact: 'Add Contact',
    newContact: 'New Contact',
    newOpportunity: 'New Opportunity',
    newProject: 'New Project',
    viewReports: 'View Reports',
    salesOverview: 'Sales Overview',
    topCustomers: 'Top Customers',
    recentTransactions: 'Recent Transactions',
    recentInvoices: 'Recent Invoices',
    upcomingTasks: 'Upcoming Tasks',
    cashFlow: 'Cash Flow',
    monthlyStats: 'Monthly Stats',
    dueDate: 'Due',
    fromPaidInvoices: 'From {count} paid invoices',
    getStarted: 'Get Started with Perfex ERP',
    getStartedDescription: 'Start by adding your first company or creating an invoice',
  },
  finance: {
    title: 'Finance',
    accounts: 'Chart of Accounts',
    accountsSubtitle: 'Manage your accounting structure',
    allAccounts: 'All Accounts',
    assets: 'Assets',
    liabilities: 'Liabilities',
    revenues: 'Revenues',
    expenses: 'Expenses',
    addAccount: 'Add Account',
    importFrenchPlan: 'Import French Plan',
    importSyscohada: 'Import SYSCOHADA',
    noAccountsFound: 'No accounts found',
    noAccountsDescription: 'Get started by importing a chart of accounts template (French Plan or SYSCOHADA) or create your first account manually.',
    invoices: 'Invoices',
    invoicesSubtitle: 'Manage your customer invoices',
    allInvoices: 'All Invoices',
    totalInvoiced: 'Total Invoiced',
    amountPaid: 'Amount Paid',
    amountDue: 'Amount Due',
    searchByInvoiceOrCustomer: 'Search by invoice number or customer...',
    createInvoice: 'Create Invoice',
    noInvoicesFound: 'No invoices found. Create your first invoice to get started.',
    payments: 'Payments',
    paymentsSubtitle: 'Track your receipts and disbursements',
    reports: 'Financial Reports',
    reportsSubtitle: 'Analyze your financial data',
    accountCode: 'Account Code',
    accountName: 'Account Name',
    accountType: 'Account Type',
    parentAccount: 'Parent Account',
    balance: 'Balance',
    debit: 'Debit',
    credit: 'Credit',
    asset: 'Asset',
    liability: 'Liability',
    equity: 'Equity',
    revenue: 'Revenue',
    expense: 'Expense',
    invoiceNumber: 'Invoice #',
    customer: 'Customer',
    issueDate: 'Issue Date',
    dueDate: 'Due Date',
    subtotal: 'Subtotal',
    tax: 'Tax',
    taxRate: 'Tax Rate',
    discount: 'Discount',
    grandTotal: 'Grand Total',
    paid: 'Paid',
    unpaid: 'Unpaid',
    overdue: 'Overdue',
    partial: 'Partial',
    cancelled: 'Cancelled',
    sent: 'Sent',
    draft: 'Draft',
    paymentMethod: 'Payment Method',
    paymentDate: 'Payment Date',
    reference: 'Reference',
    cash: 'Cash',
    bankTransfer: 'Bank Transfer',
    check: 'Check',
    creditCard: 'Credit Card',
    other: 'Other',
    totalPayments: 'Total Payments',
    count: 'Count',
    thisMonth: 'This Month',
    average: 'Average',
    recordPayment: 'Record Payment',
    searchByReferenceOrNotes: 'Search by reference or notes...',
    allMethods: 'All Methods',
    noPaymentsYet: 'No payments recorded yet',
    startByRecording: 'Get started by recording your first payment transaction.',
    notes: 'Notes',
    trialBalance: 'Trial Balance',
    balanceSheet: 'Balance Sheet',
    incomeStatement: 'Income Statement',
    generalLedger: 'General Ledger',
    startDate: 'Start Date',
    endDate: 'End Date',
    asOfDate: 'As of Date',
    generateReport: 'Generate Report',
    exportPdf: 'Export PDF',
    exportExcel: 'Export Excel',
    totalAssets: 'Total Assets',
    totalLiabilities: 'Total Liabilities',
    totalEquity: 'Total Equity',
    totalRevenue: 'Total Revenue',
    totalExpenses: 'Total Expenses',
    netIncome: 'Net Income',
  },
  crm: {
    title: 'CRM',
    companies: 'Companies',
    companiesSubtitle: 'Manage your customer, prospect, partner, and vendor companies',
    addCompany: 'Add Company',
    searchCompanies: 'Search companies by name, email, or phone...',
    allTypes: 'All Types',
    customer: 'Customer',
    prospect: 'Prospect',
    partner: 'Partner',
    vendor: 'Vendor',
    allStatus: 'All Status',
    contactInfo: 'Contact Info',
    size: 'Size',
    totalCompanies: 'Total Companies',
    customers: 'Customers',
    prospects: 'Prospects',
    noCompaniesFound: 'No companies found',
    noCompaniesDescription: 'Get started by adding your first company.',
    deleteCompanyConfirm: 'Are you sure you want to delete {name}? This will also delete all related contacts and opportunities.',
    contacts: 'Contacts',
    contactsSubtitle: 'Manage your customer and prospect contacts',
    addContact: 'Add Contact',
    searchContacts: 'Search contacts by name, email, or phone...',
    allContacts: 'All Contacts',
    position: 'Position',
    primary: 'Primary',
    noCompany: 'No company',
    totalContacts: 'Total Contacts',
    withCompany: 'With Company',
    primaryContacts: 'Primary Contacts',
    noContactsFound: 'No contacts found',
    noContactsDescription: 'Get started by adding your first contact.',
    pipeline: 'Pipeline',
    pipelineSubtitle: 'Track your sales opportunities',
    companyName: 'Company Name',
    industry: 'Industry',
    website: 'Website',
    employees: 'Employees',
    annualRevenue: 'Annual Revenue',
    contactName: 'Contact Name',
    jobTitle: 'Job Title',
    company: 'Company',
    mobile: 'Mobile',
    opportunity: 'Opportunity',
    stage: 'Stage',
    value: 'Value',
    probability: 'Probability',
    expectedClose: 'Expected Close',
    lead: 'Lead',
    qualified: 'Qualified',
    proposal: 'Proposal',
    negotiation: 'Negotiation',
    won: 'Won',
    lost: 'Lost',
    open: 'Open',
    all: 'All',
    totalValue: 'Total Value',
    openPipeline: 'Open Pipeline',
    deals: 'deals',
    opportunities: 'opportunities',
    createOpportunity: 'Create Opportunity',
    noOpportunitiesFound: 'No opportunities found',
    noOpportunitiesDescription: 'Get started by creating your first sales opportunity.',
    loadingOpportunities: 'Loading opportunities...',
  },
  projects: {
    title: 'Projects',
    subtitle: 'Manage your projects and tasks',
    projectName: 'Project Name',
    projectManager: 'Project Manager',
    startDate: 'Start Date',
    endDate: 'End Date',
    budget: 'Budget',
    progress: 'Progress',
    notStarted: 'Not Started',
    inProgress: 'In Progress',
    onHold: 'On Hold',
    completed: 'Completed',
    cancelled: 'Cancelled',
    tasks: 'Tasks',
    milestones: 'Milestones',
    team: 'Team',
    documents: 'Documents',
    newProject: 'New Project',
    searchProjects: 'Search by name or description...',
    allStatus: 'All Status',
    planning: 'Planning',
    active: 'Active',
    on_hold: 'On Hold',
    allPriorities: 'All Priorities',
    low: 'Low',
    medium: 'Medium',
    high: 'High',
    urgent: 'Urgent',
    cost: 'Cost',
    dates: 'Dates',
    start: 'Start',
    due: 'Due',
    loadingProjects: 'Loading projects...',
    noProjectsFound: 'No projects found',
    noProjectsDescription: 'Get started by creating your first project.',
    totalProjects: 'Total Projects',
    totalBudget: 'Total Budget',
  },
  inventory: {
    title: 'Inventory',
    subtitle: 'Manage your stock',
    items: 'Items',
    itemName: 'Item Name',
    sku: 'SKU',
    category: 'Category',
    quantity: 'Quantity',
    unitPrice: 'Unit Price',
    reorderLevel: 'Reorder Level',
    warehouse: 'Warehouse',
    location: 'Location',
    inStock: 'In Stock',
    outOfStock: 'Out of Stock',
    lowStock: 'Low Stock',
    movements: 'Movements',
    stockIn: 'Stock In',
    stockOut: 'Stock Out',
    transfer: 'Transfer',
    adjustment: 'Adjustment',
    newItem: 'New Item',
    totalItems: 'Total Items',
    activeItems: 'Active Items',
    warehouses: 'Warehouses',
    searchItems: 'Search by SKU, name, or description...',
    allCategories: 'All Categories',
    allStatus: 'All Status',
    loadingItems: 'Loading items...',
    costPrice: 'Cost Price',
    sellingPrice: 'Selling Price',
    unit: 'Unit',
    noItemsFound: 'No items found',
    noItemsDescription: 'Get started by adding your first inventory item.',
  },
  hr: {
    title: 'Human Resources',
    subtitle: 'Manage your employees',
    employees: 'Employees',
    employee: 'Employee',
    employeeId: 'Employee ID',
    department: 'Department',
    position: 'Position',
    hireDate: 'Hire Date',
    salary: 'Salary',
    manager: 'Manager',
    attendance: 'Attendance',
    leaves: 'Leaves',
    training: 'Training',
    performance: 'Performance',
    fullTime: 'Full Time',
    partTime: 'Part Time',
    contractor: 'Contractor',
    onLeave: 'On Leave',
    newEmployee: 'New Employee',
    searchEmployees: 'Search employees by name, email, or employee number...',
    allDepartments: 'All Departments',
    allTypes: 'All Types',
    allStatus: 'All Status',
    totalEmployees: 'Total Employees',
    activeEmployees: 'Active Employees',
    departments: 'Departments',
    pendingLeave: 'Pending Leave',
    loadingEmployees: 'Loading employees...',
    employeeNumber: 'Employee #',
    type: 'Type',
    noEmployeesFound: 'No employees found',
    noEmployeesDescription: 'Get started by adding your first employee. Manage employee information, track employment details, and maintain HR records efficiently.',
    intern: 'Intern',
    contract: 'Contract',
    full_time: 'Full Time',
    part_time: 'Part Time',
  },
  procurement: {
    title: 'Procurement',
    subtitle: 'Manage your suppliers and orders',
    suppliers: 'Suppliers',
    supplierName: 'Supplier Name',
    purchaseOrders: 'Purchase Orders',
    poNumber: 'PO Number',
    orderDate: 'Order Date',
    deliveryDate: 'Delivery Date',
    terms: 'Terms',
    approved: 'Approved',
    received: 'Received',
    addSupplier: 'Add Supplier',
    searchSuppliers: 'Search suppliers...',
    totalSuppliers: 'Total Suppliers',
    activeSuppliers: 'Active Suppliers',
    pendingOrders: 'Pending Orders',
    loadingSuppliers: 'Loading suppliers...',
    supplierNumber: 'Supplier #',
    rating: 'Rating',
    noSuppliersFound: 'No suppliers found',
    noSuppliersDescription: 'Get started by adding your first supplier to the database.',
  },
  sales: {
    title: 'Sales',
    subtitle: 'Manage your customer orders',
    salesOrders: 'Sales Orders',
    soNumber: 'SO Number',
    quotations: 'Quotations',
    orderDate: 'Order Date',
    shipDate: 'Ship Date',
    shipped: 'Shipped',
    delivered: 'Delivered',
    createOrder: 'Create Order',
    searchOrders: 'Search orders...',
    totalOrders: 'Total Orders',
    draftOrders: 'Draft Orders',
    confirmedOrders: 'Confirmed Orders',
    totalRevenue: 'Total Revenue',
    loadingOrders: 'Loading sales orders...',
    orderNumber: 'Order #',
    expectedDelivery: 'Expected Delivery',
    subtotal: 'Subtotal',
    tax: 'Tax',
    allStatuses: 'All Statuses',
    draft: 'Draft',
    confirmed: 'Confirmed',
    processing: 'Processing',
    cancelled: 'Cancelled',
    noOrdersFound: 'No sales orders found',
    noOrdersDescription: 'Get started by creating your first sales order for a customer.',
  },
  manufacturing: {
    title: 'Manufacturing',
    subtitle: 'Manage your work orders',
    workOrders: 'Work Orders',
    workOrdersSubtitle: 'Manage production orders and manufacturing',
    woNumber: 'WO #',
    product: 'Product',
    quantity: 'Quantity',
    scheduledDate: 'Scheduled Date',
    completedDate: 'Completed Date',
    bom: 'Bill of Materials',
    routing: 'Routing',
    planned: 'Planned',
    released: 'Released',
    inProduction: 'In Production',
    qualityCheck: 'Quality Check',
    createWorkOrder: 'Create Work Order',
    searchWorkOrders: 'Search work orders...',
    totalBOMs: 'Total BOMs',
    activeBOMs: 'Active BOMs',
    totalWorkOrders: 'Total Work Orders',
    inProgress: 'In Progress',
    loadingWorkOrders: 'Loading work orders...',
    scheduledStart: 'Scheduled Start',
    scheduledEnd: 'Scheduled End',
    qtyPlanned: 'Qty Planned',
    qtyProduced: 'Qty Produced',
    allStatuses: 'All Statuses',
    allPriorities: 'All Priorities',
    draft: 'Draft',
    cancelled: 'Cancelled',
    low: 'Low',
    normal: 'Normal',
    high: 'High',
    urgent: 'Urgent',
    noWorkOrdersFound: 'No work orders found',
    noWorkOrdersDescription: 'Get started by creating your first work order for production.',
  },
  assets: {
    title: 'Assets',
    subtitle: 'Manage your fixed assets',
    fixedAssets: 'Fixed Assets',
    assetName: 'Asset Name',
    assetCode: 'Asset Code',
    purchaseDate: 'Purchase Date',
    purchaseValue: 'Purchase Value',
    currentValue: 'Current Value',
    depreciation: 'Depreciation',
    depreciationMethod: 'Depreciation Method',
    usefulLife: 'Useful Life',
    salvageValue: 'Salvage Value',
    linear: 'Straight Line',
    declining: 'Declining Balance',
    addAsset: 'Add Asset',
    searchAssets: 'Search assets...',
    totalAssets: 'Total Assets',
    activeAssets: 'Active Assets',
    totalValue: 'Total Value',
    pendingMaintenance: 'Pending Maintenance',
    loadingAssets: 'Loading assets...',
    assetNumber: 'Asset #',
    location: 'Location',
    purchaseCost: 'Purchase Cost',
    allStatuses: 'All Statuses',
    active: 'Active',
    disposed: 'Disposed',
    sold: 'Sold',
    donated: 'Donated',
    lost: 'Lost',
    noAssetsFound: 'No assets found',
    noAssetsDescription: 'Get started by adding your first fixed asset to track.',
  },
  workflows: {
    title: 'Workflow Automation',
    subtitle: 'Manage workflows, approvals, webhooks, and integrations',
    workflows: 'Workflows',
    workflowName: 'Workflow Name',
    trigger: 'Trigger',
    actions: 'Actions',
    conditions: 'Conditions',
    enabled: 'Enabled',
    disabled: 'Disabled',
    apiKeys: 'API Keys',
    webhooks: 'Webhooks',
    activityFeed: 'Activity Feed',
    createApiKey: 'Create API Key',
    createWebhook: 'Create Webhook',
    createWorkflow: 'Create Workflow',
    totalWorkflows: 'Total Workflows',
    activeWorkflows: 'active',
    pendingApprovals: 'Pending Approvals',
    ofTotal: 'of',
    total: 'total',
    activeWebhooks: 'Active Webhooks',
    tags: 'Tags',
    approvals: 'Approvals',
    searchWorkflows: 'Search workflows...',
    allEntityTypes: 'All Entity Types',
    invoice: 'Invoice',
    purchaseOrder: 'Purchase Order',
    expense: 'Expense',
    opportunity: 'Opportunity',
    loadingWorkflows: 'Loading workflows...',
    entityType: 'Entity Type',
    priority: 'Priority',
    created: 'Created',
    active: 'Active',
    inactive: 'Inactive',
    noWorkflowsFound: 'No workflows found',
    noWorkflowsDescription: 'Create your first workflow to automate business processes',
    searchWebhooks: 'Search webhooks...',
    loadingWebhooks: 'Loading webhooks...',
    url: 'URL',
    events: 'Events',
    event: 'event',
    lastTriggered: 'Last Triggered',
    never: 'Never',
    noWebhooksFound: 'No webhooks found',
    noWebhooksDescription: 'Create your first webhook to receive event notifications',
    searchApiKeys: 'Search API keys...',
    loadingApiKeys: 'Loading API keys...',
    permissions: 'Permissions',
    permission: 'permission',
    rateLimit: 'Rate Limit',
    perHour: '/hour',
    expires: 'Expires',
    lastUsed: 'Last Used',
    noApiKeysFound: 'No API keys found',
    noApiKeysDescription: 'Create your first API key for programmatic access',
    approvalsComingSoon: 'Approvals management coming soon',
    tagsComingSoon: 'Tags management coming soon',
  },
  integrations: {
    title: 'Integrations',
    subtitle: 'Connect your external services',
    connectors: 'Connectors',
    connected: 'Connected',
    disconnected: 'Disconnected',
    configure: 'Configure',
    tunisian: 'Tunisian Integrations',
    apiConfig: 'API Configuration',
  },
  audit: {
    title: 'Smart Audit',
    subtitle: 'AI-assisted audit and compliance',
    dashboard: 'Dashboard',
    tasks: 'Audit Tasks',
    riskAssessment: 'Risk Assessment',
    complianceCopilot: 'Compliance Copilot',
    commonalityStudy: 'Commonality Study',
    riskScore: 'Risk Score',
    compliance: 'Compliance',
    findings: 'Findings',
    recommendations: 'Recommendations',
    critical: 'Critical',
    high: 'High',
    medium: 'Medium',
    low: 'Low',
    // Dashboard
    smartAuditSystem: 'Smart Audit System',
    smartAuditSubtitle: 'AI-powered intelligent audit system',
    auditTasks: 'Audit Tasks',
    pending: 'pending',
    averageRiskScore: 'Average Risk Score',
    highRiskEntities: 'high risk entities',
    complianceRate: 'Compliance Rate',
    isoStandards: 'ISO 9001 & standards',
    proposalsInProgress: 'Proposals in Progress',
    generatedByAI: 'AI generated',
    newTask: 'New Task',
    last7days: 'Last 7 days',
    last30days: 'Last 30 days',
    last90days: 'Last 90 days',
    // Modules
    ef1Title: 'EF1: Risk Assessment',
    ef1Description: 'Dynamic quality risk assessment model with AI analysis',
    ef1Feature1: 'NLP data analysis',
    ef1Feature2: 'Risk score 0-100',
    ef1Feature3: 'Auto task generation',
    ef2Title: 'EF2: Compliance Copilot',
    ef2Description: 'AI assistant for manufacturing compliance (ISO 9001, OSHA)',
    ef2Feature1: 'Chat with knowledge base',
    ef2Feature2: 'Compliance verification',
    ef2Feature3: 'Actionable insights',
    ef3Title: 'EF3: Commonality Analysis',
    ef3Description: 'ReAct agent for pattern analysis and improvement recommendations',
    ef3Feature1: 'ReAct framework',
    ef3Feature2: 'Variant analysis',
    ef3Feature3: 'Improvement proposals',
    recentTasks: 'Recent Tasks',
    viewAll: 'View all',
    noRecentTasks: 'No recent tasks',
    createFirstTask: 'Create a first task',
    aiInsights: 'AI Insights',
    noInsightsAvailable: 'No insights available',
    launchRiskAssessment: 'Launch a risk assessment to generate insights',
    riskMap: 'Risk Map',
    quality: 'Quality',
    process: 'Process',
    suppliers: 'Suppliers',
    riskScoreLabel: 'Risk score',
    // Tasks page
    tasksTitle: 'Audit Tasks',
    tasksSubtitle: 'Manage and track your quality audit tasks',
    searchTask: 'Search a task...',
    allStatuses: 'All statuses',
    inProgress: 'In progress',
    completed: 'Completed',
    cancelled: 'Cancelled',
    allTypes: 'All types',
    qualityType: 'Quality',
    processType: 'Process',
    supplierType: 'Supplier',
    safetyType: 'Safety',
    complianceType: 'Compliance',
    noAuditTasks: 'No audit tasks',
    noAuditTasksDescription: 'Create your first audit task or launch a risk assessment.',
    aiAssessment: 'AI Assessment',
    task: 'Task',
    type: 'Type',
    priority: 'Priority',
    risk: 'Risk',
    dueDate: 'Due date',
    aiGenerated: 'AI Generated',
    previous: 'Previous',
    next: 'Next',
    pageOf: 'Page {page} of {total}',
    // Risk Assessment page (EF1)
    ef1DynamicRiskTitle: 'EF1: Dynamic Risk Assessment',
    ef1DynamicRiskSubtitle: 'AI analysis of quality risks with automatic task generation',
    workOrder: 'Work Order',
    supplier: 'Supplier',
    product: 'Product',
    facility: 'Facility',
    analysisInProgress: 'Analysis in progress...',
    launchAssessment: 'Launch assessment',
    latestAssessment: 'Latest Assessment',
    overallScore: 'Overall Score',
    generateTasks: 'Generate Tasks',
    identifiedRiskFactors: 'Identified Risk Factors',
    noSpecificRiskFactors: 'No specific risk factors identified',
    aiRecommendations: 'AI Recommendations',
    noRecommendations: 'No recommendations available',
    assessmentHistory: 'Assessment History',
    number: 'Number',
    score: 'Score',
    tasksLabel: 'Tasks',
    generated: 'generated',
    noAssessments: 'No risk assessments. Launch your first analysis.',
    // Compliance Copilot page (EF2)
    ef2CopilotTitle: 'EF2: Compliance Copilot',
    ef2CopilotSubtitle: 'AI assistant for ISO 9001, OSHA and internal standards compliance',
    chat: 'Chat',
    knowledgeBase: 'Knowledge Base',
    welcomeToCopilot: 'Welcome to Compliance Copilot',
    copilotDescription: 'Ask your questions about ISO 9001, ISO 14001, OSHA standards, or internal quality procedures.',
    suggestion1: 'What are the ISO 9001 requirements for documentation?',
    suggestion2: 'How to manage a major non-conformity?',
    suggestion3: 'Internal audit procedure',
    sources: 'Sources',
    askQuestion: 'Ask your compliance question...',
    searchKnowledgeBase: 'Search the knowledge base...',
    add: 'Add',
    emptyKnowledgeBase: 'Empty knowledge base',
    addStandardsProcedures: 'Add standards, procedures and compliance guides.',
    consultations: 'consultations',
    // Commonality Study page (EF3)
    ef3Subtitle: 'ReAct agent for pattern identification and improvement recommendations',
    newStudy: 'New Study',
    studyTitle: 'Study title (optional)',
    defectAnalysis: 'Defect Analysis',
    supplierComparison: 'Supplier Comparison',
    processImprovement: 'Process Improvement',
    rootCauseAnalysis: 'Root Cause Analysis',
    reactAnalysisInProgress: 'ReAct analysis in progress...',
    launchAnalysis: 'Launch analysis',
    commonalityStudies: 'Commonality Studies',
    study: 'Study',
    patterns: 'Patterns',
    identified: 'identified',
    approval: 'Approval',
    viewDetails: 'View details',
    approve: 'Approve',
    reject: 'Reject',
    noStudies: 'No studies. Launch your first ReAct analysis.',
    reactTrace: 'ReAct Trace',
    step: 'Step',
    thought: 'Thought',
    action: 'Action',
    observation: 'Observation',
    patternsIdentified: 'Patterns Identified',
    frequency: 'Frequency',
    confidence: 'Confidence',
    supplierInsights: 'Supplier Insights',
    issues: 'Issues',
  },
  recipes: {
    title: 'Recipes',
    subtitle: 'Manage your recipes, formulations and technical sheets',
    recipeCards: 'Recipe Cards',
    recipeName: 'Recipe Name',
    ingredients: 'Ingredients',
    instructions: 'Instructions',
    yield: 'Yield',
    servings: 'Servings',
    prepTime: 'Prep Time',
    cookTime: 'Cook Time',
    totalTime: 'Total Time',
    costPerServing: 'Cost per Serving',
    nutritionalInfo: 'Nutritional Info',
    allergens: 'Allergens',
    newRecipe: 'New Recipe',
    totalRecipes: 'Total Recipes',
    activeRecipes: 'Active',
    draftRecipes: 'Drafts',
    categories: 'Categories',
    searchRecipe: 'Search a recipe...',
    allStatuses: 'All statuses',
    allCategories: 'All categories',
    active: 'Active',
    draft: 'Draft',
    archived: 'Archived',
    sellingPrice: 'Selling price',
    view: 'View',
    noRecipes: 'No recipes',
    noRecipesDescription: 'Get started by creating your first recipe.',
    createRecipe: 'Create a recipe',
    deleteRecipe: 'Delete recipe',
    deleteConfirmation: 'Are you sure you want to delete',
    deleteWarning: 'This action is irreversible.',
    deleting: 'Deleting...',
  },
  traceability: {
    title: 'Traceability',
    subtitle: 'Lots and HACCP compliance',
    lots: 'Lots',
    lotNumber: 'Lot Number',
    batchNumber: 'Batch Number',
    productionDate: 'Production Date',
    expiryDate: 'Expiry Date',
    haccp: 'HACCP',
    ccp: 'Critical Control Points',
    monitoring: 'Monitoring',
    corrective: 'Corrective Actions',
    verification: 'Verification',
    temperature: 'Temperature',
    humidity: 'Humidity',
  },
  payroll: {
    title: 'Payroll Management',
    subtitle: 'Manage salaries and payslips',
    periods: 'Pay Periods',
    payslips: 'Payslips',
    employees: 'Employees',
    grossSalary: 'Gross Salary',
    netSalary: 'Net Salary',
    deductions: 'Deductions',
    contributions: 'Contributions',
    bonuses: 'Bonuses',
    overtime: 'Overtime',
    taxes: 'Taxes',
    cnss: 'Social Security',
    periodMonth: 'Month',
    periodYear: 'Year',
    generate: 'Generate',
    validate: 'Validate',
    process: 'Process',
  },
  settings: {
    title: 'Settings',
    subtitle: 'Configure your platform',
    platform: 'Platform Settings',
    modules: 'Module Management',
    language: 'Platform Language',
    country: 'Country',
    currency: 'Default Currency',
    timezone: 'Timezone',
    dateFormat: 'Date Format',
    numberFormat: 'Number Format',
    theme: 'Theme',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    system: 'System',
    security: 'Security',
    backup: 'Backup',
    import: 'Data Import',
    export: 'Data Export',
    users: 'Users',
    roles: 'Roles',
    permissions: 'Permissions',
    organization: 'Organization',
    companyInfo: 'Company Information',
    billing: 'Billing',
    subscription: 'Subscription',
    modulesList: 'Modules List',
    enableModule: 'Enable Module',
    disableModule: 'Disable Module',
  },
  help: {
    title: 'Help Center',
    subtitle: 'Documentation and support',
    gettingStarted: 'Getting Started',
    faq: 'FAQ',
    moduleGuides: 'Module Guides',
    searchHelp: 'Search help',
    contactSupport: 'Contact Support',
    documentation: 'Documentation',
    tutorials: 'Tutorials',
    videos: 'Videos',
    community: 'Community',
  },
  ai: {
    title: 'Artificial Intelligence',
    subtitle: 'Advanced AI features',
    assistant: 'AI Assistant',
    predictions: 'Predictions',
    insights: 'Insights',
    automation: 'Automation',
    askAnything: 'Ask anything...',
    generating: 'Generating...',
    suggestions: 'Suggestions',
  },
  languages: {
    fr: 'Français',
    en: 'English',
    ar: 'العربية',
  },
  footer: {
    allRightsReserved: 'All rights reserved',
    documentation: 'Documentation',
    support: 'Support',
  },
};

// Arabic translations
const ar: Translations = {
  common: {
    save: 'حفظ',
    cancel: 'إلغاء',
    delete: 'حذف',
    edit: 'تعديل',
    add: 'إضافة',
    create: 'إنشاء',
    update: 'تحديث',
    search: 'بحث',
    filter: 'تصفية',
    loading: 'جاري التحميل...',
    error: 'خطأ',
    success: 'نجاح',
    confirm: 'تأكيد',
    back: 'رجوع',
    next: 'التالي',
    previous: 'السابق',
    close: 'إغلاق',
    yes: 'نعم',
    no: 'لا',
    actions: 'الإجراءات',
    status: 'الحالة',
    priority: 'الأولوية',
    date: 'التاريخ',
    name: 'الاسم',
    email: 'البريد الإلكتروني',
    phone: 'الهاتف',
    address: 'العنوان',
    description: 'الوصف',
    amount: 'المبلغ',
    total: 'المجموع',
    settings: 'الإعدادات',
    language: 'اللغة',
    view: 'عرض',
    viewAll: 'عرض الكل',
    details: 'التفاصيل',
    export: 'تصدير',
    import: 'استيراد',
    refresh: 'تحديث',
    noData: 'لا توجد بيانات',
    noResults: 'لا توجد نتائج',
    all: 'الكل',
    active: 'نشط',
    inactive: 'غير نشط',
    pending: 'معلق',
    completed: 'مكتمل',
    draft: 'مسودة',
    new: 'جديد',
    code: 'الرمز',
    type: 'النوع',
    currency: 'العملة',
    country: 'البلد',
    timezone: 'المنطقة الزمنية',
    dateFormat: 'تنسيق التاريخ',
    numberFormat: 'تنسيق الأرقام',
    required: 'مطلوب',
    optional: 'اختياري',
    select: 'اختر',
    submit: 'إرسال',
    reset: 'إعادة تعيين',
    clear: 'مسح',
    apply: 'تطبيق',
    showing: 'عرض',
    of: 'من',
    results: 'نتائج',
    page: 'صفحة',
    perPage: 'لكل صفحة',
    sortBy: 'ترتيب حسب',
    ascending: 'تصاعدي',
    descending: 'تنازلي',
    notifications: 'الإشعارات',
    allRightsReserved: 'جميع الحقوق محفوظة',
    documentation: 'التوثيق',
    support: 'الدعم',
    user: 'مستخدم',
  },
  auth: {
    login: 'تسجيل الدخول',
    logout: 'تسجيل الخروج',
    register: 'إنشاء حساب',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    forgotPassword: 'نسيت كلمة المرور؟',
    rememberMe: 'تذكرني',
    noAccount: 'ليس لديك حساب؟',
    hasAccount: 'لديك حساب بالفعل؟',
    signUp: 'إنشاء حساب',
    signIn: 'تسجيل الدخول',
    welcome: 'مرحبا',
    welcomeBack: 'مرحبا بعودتك',
    createAccount: 'إنشاء حساب',
    enterCredentials: 'أدخل بيانات الدخول للمتابعة',
    firstName: 'الاسم الأول',
    lastName: 'اسم العائلة',
  },
  profile: {
    title: 'ملفي الشخصي',
    subtitle: 'إدارة معلوماتك الشخصية',
    personalInfo: 'المعلومات الشخصية',
    firstName: 'الاسم الأول',
    lastName: 'اسم العائلة',
    email: 'البريد الإلكتروني',
    avatar: 'صورة الملف الشخصي',
    avatarUrl: 'رابط الصورة',
    changePassword: 'تغيير كلمة المرور',
    currentPassword: 'كلمة المرور الحالية',
    newPassword: 'كلمة المرور الجديدة',
    confirmPassword: 'تأكيد كلمة المرور',
    preferences: 'التفضيلات',
    language: 'اللغة',
    theme: 'السمة',
    notifications: 'الإشعارات',
    updateSuccess: 'تم تحديث الملف الشخصي بنجاح',
    updateError: 'خطأ في تحديث الملف الشخصي',
    security: 'الأمان',
    accountSettings: 'إعدادات الحساب',
  },
  nav: {
    dashboard: 'لوحة التحكم',
    finance: 'المالية',
    crm: 'إدارة العملاء',
    projects: 'المشاريع',
    inventory: 'المخزون',
    hr: 'الموارد البشرية',
    procurement: 'المشتريات',
    sales: 'المبيعات',
    manufacturing: 'الإنتاج',
    assets: 'الأصول',
    workflows: 'الأتمتة',
    integrations: 'التكاملات',
    help: 'المساعدة',
    settings: 'الإعدادات',
    audit: 'التدقيق الذكي',
    recipes: 'الوصفات',
    traceability: 'التتبع',
    payroll: 'الرواتب',
    ai: 'الذكاء الاصطناعي',
  },
  sidebar: {
    accounts: 'الحسابات',
    invoices: 'الفواتير',
    payments: 'المدفوعات',
    reports: 'التقارير',
    companies: 'الشركات',
    contacts: 'جهات الاتصال',
    pipeline: 'خط المبيعات',
    opportunities: 'الفرص',
    allProjects: 'جميع المشاريع',
    tasks: 'المهام',
    inventoryItems: 'عناصر المخزون',
    warehouses: 'المستودعات',
    movements: 'الحركات',
    employees: 'الموظفين',
    departments: 'الأقسام',
    attendance: 'الحضور',
    leaves: 'الإجازات',
    suppliers: 'الموردين',
    purchaseOrders: 'أوامر الشراء',
    salesOrders: 'أوامر البيع',
    quotations: 'عروض الأسعار',
    workOrders: 'أوامر العمل',
    bom: 'قائمة المواد',
    fixedAssets: 'الأصول الثابتة',
    depreciation: 'الإهلاك',
    workflows: 'سير العمل',
    activityFeed: 'سجل النشاط',
    apiKeys: 'مفاتيح API',
    webhooks: 'Webhooks',
    aiFeatures: 'ميزات الذكاء الاصطناعي',
    aiAssistant: 'المساعد الذكي',
    auditDashboard: 'لوحة التدقيق',
    auditTasks: 'مهام التدقيق',
    riskAssessment: 'تقييم المخاطر',
    complianceCopilot: 'مساعد الامتثال',
    commonalityStudy: 'دراسة القواسم المشتركة',
    recipeCards: 'بطاقات الوصفات',
    ingredients: 'المكونات',
    lotsHaccp: 'الدفعات و HACCP',
    qualityControl: 'مراقبة الجودة',
    payrollManagement: 'إدارة الرواتب',
    payslips: 'كشوف المرتبات',
    connectors: 'الموصلات',
    moduleManagement: 'إدارة الوحدات',
    platformSettings: 'إعدادات المنصة',
    helpCenter: 'مركز المساعدة',
    gettingStarted: 'البدء',
    faq: 'الأسئلة الشائعة',
    moduleGuides: 'أدلة الوحدات',
  },
  dashboard: {
    title: 'لوحة التحكم',
    subtitle: 'نظرة عامة على نشاطك',
    welcome: 'مرحبا',
    welcomeBack: 'مرحبا بعودتك',
    totalRevenue: 'إجمالي الإيرادات',
    totalExpenses: 'إجمالي المصروفات',
    netProfit: 'صافي الربح',
    pendingInvoices: 'الفواتير المعلقة',
    unpaidInvoices: 'الفواتير غير المدفوعة',
    overdue: 'متأخرة',
    activeCompanies: 'الشركات النشطة',
    totalContacts: 'إجمالي جهات الاتصال',
    openPipeline: 'خط الأنابيب المفتوح',
    opportunities: 'الفرص',
    recentActivity: 'النشاط الأخير',
    quickActions: 'إجراءات سريعة',
    newInvoice: 'فاتورة جديدة',
    createInvoice: 'إنشاء فاتورة',
    addCompany: 'إضافة شركة',
    addContact: 'إضافة جهة اتصال',
    newContact: 'جهة اتصال جديدة',
    newOpportunity: 'فرصة جديدة',
    newProject: 'مشروع جديد',
    viewReports: 'عرض التقارير',
    salesOverview: 'نظرة عامة على المبيعات',
    topCustomers: 'أفضل العملاء',
    recentTransactions: 'المعاملات الأخيرة',
    recentInvoices: 'الفواتير الأخيرة',
    upcomingTasks: 'المهام القادمة',
    cashFlow: 'التدفق النقدي',
    monthlyStats: 'إحصائيات شهرية',
    dueDate: 'تاريخ الاستحقاق',
    fromPaidInvoices: 'من {count} فاتورة مدفوعة',
    getStarted: 'ابدأ مع Perfex ERP',
    getStartedDescription: 'ابدأ بإضافة أول شركة أو إنشاء فاتورة',
  },
  finance: {
    title: 'المالية',
    accounts: 'دليل الحسابات',
    accountsSubtitle: 'إدارة هيكلك المحاسبي',
    allAccounts: 'جميع الحسابات',
    assets: 'الأصول',
    liabilities: 'الخصوم',
    revenues: 'الإيرادات',
    expenses: 'المصروفات',
    addAccount: 'إضافة حساب',
    importFrenchPlan: 'استيراد الخطة الفرنسية',
    importSyscohada: 'استيراد SYSCOHADA',
    noAccountsFound: 'لا توجد حسابات',
    noAccountsDescription: 'ابدأ باستيراد نموذج دليل حسابات (الخطة الفرنسية أو SYSCOHADA) أو أنشئ أول حساب يدوياً.',
    invoices: 'الفواتير',
    invoicesSubtitle: 'إدارة فواتير العملاء',
    allInvoices: 'جميع الفواتير',
    totalInvoiced: 'إجمالي الفواتير',
    amountPaid: 'المبلغ المدفوع',
    amountDue: 'المبلغ المستحق',
    searchByInvoiceOrCustomer: 'البحث برقم الفاتورة أو العميل...',
    createInvoice: 'إنشاء فاتورة',
    noInvoicesFound: 'لا توجد فواتير. أنشئ أول فاتورة للبدء.',
    payments: 'المدفوعات',
    paymentsSubtitle: 'تتبع المقبوضات والمدفوعات',
    reports: 'التقارير المالية',
    reportsSubtitle: 'تحليل بياناتك المالية',
    accountCode: 'رمز الحساب',
    accountName: 'اسم الحساب',
    accountType: 'نوع الحساب',
    parentAccount: 'الحساب الأصلي',
    balance: 'الرصيد',
    debit: 'مدين',
    credit: 'دائن',
    asset: 'أصول',
    liability: 'خصوم',
    equity: 'حقوق الملكية',
    revenue: 'إيرادات',
    expense: 'مصروفات',
    invoiceNumber: 'رقم الفاتورة',
    customer: 'العميل',
    issueDate: 'تاريخ الإصدار',
    dueDate: 'تاريخ الاستحقاق',
    subtotal: 'المجموع الفرعي',
    tax: 'الضريبة',
    taxRate: 'نسبة الضريبة',
    discount: 'الخصم',
    grandTotal: 'المجموع الكلي',
    paid: 'مدفوع',
    unpaid: 'غير مدفوع',
    overdue: 'متأخر',
    partial: 'جزئي',
    cancelled: 'ملغى',
    sent: 'مرسل',
    draft: 'مسودة',
    paymentMethod: 'طريقة الدفع',
    paymentDate: 'تاريخ الدفع',
    reference: 'المرجع',
    cash: 'نقدي',
    bankTransfer: 'تحويل بنكي',
    check: 'شيك',
    creditCard: 'بطاقة ائتمان',
    other: 'أخرى',
    totalPayments: 'إجمالي المدفوعات',
    count: 'العدد',
    thisMonth: 'هذا الشهر',
    average: 'المتوسط',
    recordPayment: 'تسجيل دفعة',
    searchByReferenceOrNotes: 'البحث بالمرجع أو الملاحظات...',
    allMethods: 'جميع الطرق',
    noPaymentsYet: 'لا توجد مدفوعات مسجلة بعد',
    startByRecording: 'ابدأ بتسجيل أول عملية دفع.',
    notes: 'ملاحظات',
    trialBalance: 'ميزان المراجعة',
    balanceSheet: 'الميزانية العمومية',
    incomeStatement: 'قائمة الدخل',
    generalLedger: 'دفتر الأستاذ',
    startDate: 'تاريخ البداية',
    endDate: 'تاريخ النهاية',
    asOfDate: 'كما في تاريخ',
    generateReport: 'إنشاء التقرير',
    exportPdf: 'تصدير PDF',
    exportExcel: 'تصدير Excel',
    totalAssets: 'إجمالي الأصول',
    totalLiabilities: 'إجمالي الخصوم',
    totalEquity: 'إجمالي حقوق الملكية',
    totalRevenue: 'إجمالي الإيرادات',
    totalExpenses: 'إجمالي المصروفات',
    netIncome: 'صافي الدخل',
  },
  crm: {
    title: 'إدارة العملاء',
    companies: 'الشركات',
    companiesSubtitle: 'إدارة الشركات العملاء والمحتملين والشركاء',
    addCompany: 'إضافة شركة',
    searchCompanies: 'البحث بالاسم أو البريد أو الهاتف...',
    allTypes: 'جميع الأنواع',
    customer: 'عميل',
    prospect: 'محتمل',
    partner: 'شريك',
    vendor: 'مورد',
    allStatus: 'جميع الحالات',
    contactInfo: 'معلومات الاتصال',
    size: 'الحجم',
    totalCompanies: 'إجمالي الشركات',
    customers: 'العملاء',
    prospects: 'المحتملين',
    noCompaniesFound: 'لا توجد شركات',
    noCompaniesDescription: 'ابدأ بإضافة أول شركة.',
    deleteCompanyConfirm: 'هل أنت متأكد من حذف {name}؟ سيتم حذف جميع جهات الاتصال والفرص المرتبطة.',
    contacts: 'جهات الاتصال',
    contactsSubtitle: 'إدارة جهات اتصال العملاء والمحتملين',
    addContact: 'إضافة جهة اتصال',
    searchContacts: 'البحث بالاسم أو البريد أو الهاتف...',
    allContacts: 'جميع جهات الاتصال',
    position: 'المنصب',
    primary: 'رئيسي',
    noCompany: 'بدون شركة',
    totalContacts: 'إجمالي جهات الاتصال',
    withCompany: 'مع شركة',
    primaryContacts: 'جهات الاتصال الرئيسية',
    noContactsFound: 'لا توجد جهات اتصال',
    noContactsDescription: 'ابدأ بإضافة أول جهة اتصال.',
    pipeline: 'خط المبيعات',
    pipelineSubtitle: 'تتبع فرص المبيعات',
    companyName: 'اسم الشركة',
    industry: 'القطاع',
    website: 'الموقع الإلكتروني',
    employees: 'الموظفين',
    annualRevenue: 'الإيرادات السنوية',
    contactName: 'اسم جهة الاتصال',
    jobTitle: 'المسمى الوظيفي',
    company: 'الشركة',
    mobile: 'الجوال',
    opportunity: 'فرصة',
    stage: 'المرحلة',
    value: 'القيمة',
    probability: 'الاحتمالية',
    expectedClose: 'الإغلاق المتوقع',
    lead: 'عميل محتمل',
    qualified: 'مؤهل',
    proposal: 'عرض',
    negotiation: 'تفاوض',
    won: 'ناجح',
    lost: 'خاسر',
    open: 'مفتوح',
    all: 'الكل',
    totalValue: 'القيمة الإجمالية',
    openPipeline: 'خط المبيعات المفتوح',
    deals: 'صفقات',
    opportunities: 'فرص',
    createOpportunity: 'إنشاء فرصة',
    noOpportunitiesFound: 'لا توجد فرص',
    noOpportunitiesDescription: 'ابدأ بإنشاء أول فرصة مبيعات.',
    loadingOpportunities: 'جاري تحميل الفرص...',
  },
  projects: {
    title: 'المشاريع',
    subtitle: 'إدارة مشاريعك ومهامك',
    projectName: 'اسم المشروع',
    projectManager: 'مدير المشروع',
    startDate: 'تاريخ البداية',
    endDate: 'تاريخ النهاية',
    budget: 'الميزانية',
    progress: 'التقدم',
    notStarted: 'لم يبدأ',
    inProgress: 'قيد التنفيذ',
    onHold: 'معلق',
    completed: 'مكتمل',
    cancelled: 'ملغى',
    tasks: 'المهام',
    milestones: 'المعالم',
    team: 'الفريق',
    documents: 'الوثائق',
    newProject: 'مشروع جديد',
    searchProjects: 'البحث حسب الاسم أو الوصف...',
    allStatus: 'جميع الحالات',
    planning: 'تخطيط',
    active: 'نشط',
    on_hold: 'معلق',
    allPriorities: 'جميع الأولويات',
    low: 'منخفضة',
    medium: 'متوسطة',
    high: 'عالية',
    urgent: 'عاجلة',
    cost: 'التكلفة',
    dates: 'التواريخ',
    start: 'البداية',
    due: 'الاستحقاق',
    loadingProjects: 'جاري تحميل المشاريع...',
    noProjectsFound: 'لا توجد مشاريع',
    noProjectsDescription: 'ابدأ بإنشاء مشروعك الأول.',
    totalProjects: 'إجمالي المشاريع',
    totalBudget: 'إجمالي الميزانية',
  },
  inventory: {
    title: 'المخزون',
    subtitle: 'إدارة المخزون',
    items: 'العناصر',
    itemName: 'اسم العنصر',
    sku: 'رمز المنتج',
    category: 'الفئة',
    quantity: 'الكمية',
    unitPrice: 'سعر الوحدة',
    reorderLevel: 'مستوى إعادة الطلب',
    warehouse: 'المستودع',
    location: 'الموقع',
    inStock: 'متوفر',
    outOfStock: 'نفذ من المخزون',
    lowStock: 'مخزون منخفض',
    movements: 'الحركات',
    stockIn: 'إدخال',
    stockOut: 'إخراج',
    transfer: 'تحويل',
    adjustment: 'تعديل',
    newItem: 'عنصر جديد',
    totalItems: 'إجمالي العناصر',
    activeItems: 'العناصر النشطة',
    warehouses: 'المستودعات',
    searchItems: 'البحث حسب الرمز أو الاسم أو الوصف...',
    allCategories: 'جميع الفئات',
    allStatus: 'جميع الحالات',
    loadingItems: 'جاري تحميل العناصر...',
    costPrice: 'سعر التكلفة',
    sellingPrice: 'سعر البيع',
    unit: 'الوحدة',
    noItemsFound: 'لا توجد عناصر',
    noItemsDescription: 'ابدأ بإضافة أول عنصر في المخزون.',
  },
  hr: {
    title: 'الموارد البشرية',
    subtitle: 'إدارة الموظفين',
    employees: 'الموظفين',
    employee: 'موظف',
    employeeId: 'رقم الموظف',
    department: 'القسم',
    position: 'المنصب',
    hireDate: 'تاريخ التوظيف',
    salary: 'الراتب',
    manager: 'المدير',
    attendance: 'الحضور',
    leaves: 'الإجازات',
    training: 'التدريب',
    performance: 'الأداء',
    fullTime: 'دوام كامل',
    partTime: 'دوام جزئي',
    contractor: 'متعاقد',
    onLeave: 'في إجازة',
    newEmployee: 'موظف جديد',
    searchEmployees: 'البحث عن الموظفين بالاسم أو البريد الإلكتروني أو الرقم...',
    allDepartments: 'جميع الأقسام',
    allTypes: 'جميع الأنواع',
    allStatus: 'جميع الحالات',
    totalEmployees: 'إجمالي الموظفين',
    activeEmployees: 'الموظفين النشطين',
    departments: 'الأقسام',
    pendingLeave: 'إجازات معلقة',
    loadingEmployees: 'جاري تحميل الموظفين...',
    employeeNumber: 'رقم الموظف',
    type: 'النوع',
    noEmployeesFound: 'لم يتم العثور على موظفين',
    noEmployeesDescription: 'ابدأ بإضافة أول موظف. قم بإدارة معلومات الموظفين وتتبع تفاصيل التوظيف والحفاظ على سجلات الموارد البشرية بكفاءة.',
    intern: 'متدرب',
    contract: 'عقد محدد',
    full_time: 'دوام كامل',
    part_time: 'دوام جزئي',
  },
  procurement: {
    title: 'المشتريات',
    subtitle: 'إدارة الموردين والطلبات',
    suppliers: 'الموردين',
    supplierName: 'اسم المورد',
    purchaseOrders: 'أوامر الشراء',
    poNumber: 'رقم أمر الشراء',
    orderDate: 'تاريخ الطلب',
    deliveryDate: 'تاريخ التسليم',
    terms: 'الشروط',
    approved: 'موافق عليه',
    received: 'مستلم',
    addSupplier: 'إضافة مورد',
    searchSuppliers: 'البحث عن الموردين...',
    totalSuppliers: 'إجمالي الموردين',
    activeSuppliers: 'الموردين النشطين',
    pendingOrders: 'الطلبات المعلقة',
    loadingSuppliers: 'جاري تحميل الموردين...',
    supplierNumber: 'رقم المورد',
    rating: 'التقييم',
    noSuppliersFound: 'لم يتم العثور على موردين',
    noSuppliersDescription: 'ابدأ بإضافة أول مورد إلى قاعدة البيانات.',
  },
  sales: {
    title: 'المبيعات',
    subtitle: 'إدارة طلبات العملاء',
    salesOrders: 'أوامر البيع',
    soNumber: 'رقم أمر البيع',
    quotations: 'عروض الأسعار',
    orderDate: 'تاريخ الطلب',
    shipDate: 'تاريخ الشحن',
    shipped: 'تم الشحن',
    delivered: 'تم التسليم',
    createOrder: 'إنشاء طلب',
    searchOrders: 'البحث عن الطلبات...',
    totalOrders: 'إجمالي الطلبات',
    draftOrders: 'طلبات مسودة',
    confirmedOrders: 'طلبات مؤكدة',
    totalRevenue: 'إجمالي الإيرادات',
    loadingOrders: 'جاري تحميل الطلبات...',
    orderNumber: 'رقم الطلب',
    expectedDelivery: 'التسليم المتوقع',
    subtotal: 'المجموع الفرعي',
    tax: 'الضريبة',
    allStatuses: 'جميع الحالات',
    draft: 'مسودة',
    confirmed: 'مؤكد',
    processing: 'قيد المعالجة',
    cancelled: 'ملغي',
    noOrdersFound: 'لم يتم العثور على طلبات',
    noOrdersDescription: 'ابدأ بإنشاء أول طلب بيع للعميل.',
  },
  manufacturing: {
    title: 'الإنتاج',
    subtitle: 'إدارة أوامر العمل',
    workOrders: 'أوامر العمل',
    workOrdersSubtitle: 'إدارة أوامر الإنتاج والتصنيع',
    woNumber: 'رقم أ.ع.',
    product: 'المنتج',
    quantity: 'الكمية',
    scheduledDate: 'التاريخ المجدول',
    completedDate: 'تاريخ الإنجاز',
    bom: 'قائمة المواد',
    routing: 'المسار',
    planned: 'مخطط',
    released: 'صادر',
    inProduction: 'قيد الإنتاج',
    qualityCheck: 'فحص الجودة',
    createWorkOrder: 'إنشاء أمر عمل',
    searchWorkOrders: 'البحث عن أوامر العمل...',
    totalBOMs: 'إجمالي قوائم المواد',
    activeBOMs: 'قوائم المواد النشطة',
    totalWorkOrders: 'إجمالي أوامر العمل',
    inProgress: 'قيد التنفيذ',
    loadingWorkOrders: 'جاري تحميل أوامر العمل...',
    scheduledStart: 'بداية مجدولة',
    scheduledEnd: 'نهاية مجدولة',
    qtyPlanned: 'الكمية المخططة',
    qtyProduced: 'الكمية المنتجة',
    allStatuses: 'جميع الحالات',
    allPriorities: 'جميع الأولويات',
    draft: 'مسودة',
    cancelled: 'ملغي',
    low: 'منخفضة',
    normal: 'عادية',
    high: 'عالية',
    urgent: 'عاجلة',
    noWorkOrdersFound: 'لم يتم العثور على أوامر عمل',
    noWorkOrdersDescription: 'ابدأ بإنشاء أول أمر عمل للإنتاج.',
  },
  assets: {
    title: 'الأصول',
    subtitle: 'إدارة الأصول الثابتة',
    fixedAssets: 'الأصول الثابتة',
    assetName: 'اسم الأصل',
    assetCode: 'رمز الأصل',
    purchaseDate: 'تاريخ الشراء',
    purchaseValue: 'قيمة الشراء',
    currentValue: 'القيمة الحالية',
    depreciation: 'الإهلاك',
    depreciationMethod: 'طريقة الإهلاك',
    addAsset: 'إضافة أصل',
    searchAssets: 'البحث عن الأصول...',
    totalAssets: 'إجمالي الأصول',
    activeAssets: 'الأصول النشطة',
    totalValue: 'القيمة الإجمالية',
    pendingMaintenance: 'صيانة معلقة',
    loadingAssets: 'جاري تحميل الأصول...',
    assetNumber: 'رقم الأصل',
    location: 'الموقع',
    purchaseCost: 'تكلفة الشراء',
    allStatuses: 'جميع الحالات',
    active: 'نشط',
    disposed: 'متخلص منه',
    sold: 'مباع',
    donated: 'متبرع به',
    lost: 'مفقود',
    noAssetsFound: 'لم يتم العثور على أصول',
    noAssetsDescription: 'ابدأ بإضافة أول أصل ثابت.',
    usefulLife: 'العمر الإنتاجي',
    salvageValue: 'القيمة المتبقية',
    linear: 'القسط الثابت',
    declining: 'القسط المتناقص',
  },
  workflows: {
    title: 'أتمتة سير العمل',
    subtitle: 'إدارة سير العمل والموافقات وWebhooks والتكاملات',
    workflows: 'سير العمل',
    workflowName: 'اسم سير العمل',
    trigger: 'المشغل',
    actions: 'الإجراءات',
    conditions: 'الشروط',
    enabled: 'مفعل',
    disabled: 'معطل',
    apiKeys: 'مفاتيح API',
    webhooks: 'Webhooks',
    activityFeed: 'سجل النشاط',
    createApiKey: 'إنشاء مفتاح API',
    createWebhook: 'إنشاء Webhook',
    createWorkflow: 'إنشاء سير عمل',
    totalWorkflows: 'إجمالي سير العمل',
    activeWorkflows: 'نشط',
    pendingApprovals: 'الموافقات المعلقة',
    ofTotal: 'من',
    total: 'الإجمالي',
    activeWebhooks: 'Webhooks نشطة',
    tags: 'الوسوم',
    approvals: 'الموافقات',
    searchWorkflows: 'البحث عن سير العمل...',
    allEntityTypes: 'جميع أنواع الكيانات',
    invoice: 'فاتورة',
    purchaseOrder: 'أمر شراء',
    expense: 'مصروف',
    opportunity: 'فرصة',
    loadingWorkflows: 'جاري تحميل سير العمل...',
    entityType: 'نوع الكيان',
    priority: 'الأولوية',
    created: 'تم الإنشاء',
    active: 'نشط',
    inactive: 'غير نشط',
    noWorkflowsFound: 'لم يتم العثور على سير عمل',
    noWorkflowsDescription: 'أنشئ أول سير عمل لأتمتة العمليات التجارية',
    searchWebhooks: 'البحث عن Webhooks...',
    loadingWebhooks: 'جاري تحميل Webhooks...',
    url: 'الرابط',
    events: 'الأحداث',
    event: 'حدث',
    lastTriggered: 'آخر تشغيل',
    never: 'أبداً',
    noWebhooksFound: 'لم يتم العثور على Webhooks',
    noWebhooksDescription: 'أنشئ أول Webhook لتلقي إشعارات الأحداث',
    searchApiKeys: 'البحث عن مفاتيح API...',
    loadingApiKeys: 'جاري تحميل مفاتيح API...',
    permissions: 'الصلاحيات',
    permission: 'صلاحية',
    rateLimit: 'حد المعدل',
    perHour: '/ساعة',
    expires: 'تنتهي',
    lastUsed: 'آخر استخدام',
    noApiKeysFound: 'لم يتم العثور على مفاتيح API',
    noApiKeysDescription: 'أنشئ أول مفتاح API للوصول البرمجي',
    approvalsComingSoon: 'إدارة الموافقات قريباً',
    tagsComingSoon: 'إدارة الوسوم قريباً',
  },
  integrations: {
    title: 'التكاملات',
    subtitle: 'ربط الخدمات الخارجية',
    connectors: 'الموصلات',
    connected: 'متصل',
    disconnected: 'غير متصل',
    configure: 'تكوين',
    tunisian: 'تكاملات تونس',
    apiConfig: 'تكوين API',
  },
  audit: {
    title: 'التدقيق الذكي',
    subtitle: 'تدقيق وامتثال بمساعدة الذكاء الاصطناعي',
    dashboard: 'لوحة التحكم',
    tasks: 'مهام التدقيق',
    riskAssessment: 'تقييم المخاطر',
    complianceCopilot: 'مساعد الامتثال',
    commonalityStudy: 'دراسة القواسم المشتركة',
    riskScore: 'درجة المخاطر',
    compliance: 'الامتثال',
    findings: 'النتائج',
    recommendations: 'التوصيات',
    critical: 'حرج',
    high: 'عالي',
    medium: 'متوسط',
    low: 'منخفض',
    // Dashboard
    smartAuditSystem: 'نظام التدقيق الذكي',
    smartAuditSubtitle: 'نظام تدقيق ذكي مدعوم بالذكاء الاصطناعي',
    auditTasks: 'مهام التدقيق',
    pending: 'قيد الانتظار',
    averageRiskScore: 'متوسط درجة المخاطر',
    highRiskEntities: 'كيانات عالية المخاطر',
    complianceRate: 'معدل الامتثال',
    isoStandards: 'معايير ISO 9001',
    proposalsInProgress: 'مقترحات قيد التنفيذ',
    generatedByAI: 'تم إنشاؤها بواسطة الذكاء الاصطناعي',
    newTask: 'مهمة جديدة',
    last7days: 'آخر 7 أيام',
    last30days: 'آخر 30 يوم',
    last90days: 'آخر 90 يوم',
    // Modules
    ef1Title: 'EF1: تقييم المخاطر',
    ef1Description: 'نموذج ديناميكي لتقييم مخاطر الجودة مع تحليل الذكاء الاصطناعي',
    ef1Feature1: 'تحليل NLP للبيانات',
    ef1Feature2: 'درجة المخاطر 0-100',
    ef1Feature3: 'توليد المهام تلقائياً',
    ef2Title: 'EF2: مساعد الامتثال',
    ef2Description: 'مساعد ذكاء اصطناعي للامتثال التصنيعي (ISO 9001, OSHA)',
    ef2Feature1: 'دردشة مع قاعدة المعرفة',
    ef2Feature2: 'التحقق من الامتثال',
    ef2Feature3: 'رؤى قابلة للتنفيذ',
    ef3Title: 'EF3: تحليل القواسم المشتركة',
    ef3Description: 'وكيل ReAct لتحليل الأنماط وتوصيات التحسين',
    ef3Feature1: 'إطار عمل ReAct',
    ef3Feature2: 'تحليل المتغيرات',
    ef3Feature3: 'مقترحات التحسين',
    recentTasks: 'المهام الأخيرة',
    viewAll: 'عرض الكل',
    noRecentTasks: 'لا توجد مهام حديثة',
    createFirstTask: 'إنشاء أول مهمة',
    aiInsights: 'رؤى الذكاء الاصطناعي',
    noInsightsAvailable: 'لا توجد رؤى متاحة',
    launchRiskAssessment: 'أطلق تقييم المخاطر لتوليد الرؤى',
    riskMap: 'خريطة المخاطر',
    quality: 'الجودة',
    process: 'العملية',
    suppliers: 'الموردون',
    riskScoreLabel: 'درجة المخاطر',
    // Tasks page
    tasksTitle: 'مهام التدقيق',
    tasksSubtitle: 'إدارة ومتابعة مهام تدقيق الجودة',
    searchTask: 'البحث عن مهمة...',
    allStatuses: 'جميع الحالات',
    inProgress: 'قيد التنفيذ',
    completed: 'مكتمل',
    cancelled: 'ملغي',
    allTypes: 'جميع الأنواع',
    qualityType: 'الجودة',
    processType: 'العملية',
    supplierType: 'المورد',
    safetyType: 'السلامة',
    complianceType: 'الامتثال',
    noAuditTasks: 'لا توجد مهام تدقيق',
    noAuditTasksDescription: 'أنشئ أول مهمة تدقيق أو أطلق تقييم المخاطر.',
    aiAssessment: 'تقييم الذكاء الاصطناعي',
    task: 'المهمة',
    type: 'النوع',
    priority: 'الأولوية',
    risk: 'المخاطر',
    dueDate: 'تاريخ الاستحقاق',
    aiGenerated: 'تم إنشاؤها بواسطة AI',
    previous: 'السابق',
    next: 'التالي',
    pageOf: 'صفحة {page} من {total}',
    // Risk Assessment page (EF1)
    ef1DynamicRiskTitle: 'EF1: تقييم المخاطر الديناميكي',
    ef1DynamicRiskSubtitle: 'تحليل الذكاء الاصطناعي لمخاطر الجودة مع توليد المهام تلقائياً',
    workOrder: 'أمر العمل',
    supplier: 'المورد',
    product: 'المنتج',
    facility: 'المنشأة',
    analysisInProgress: 'التحليل جارٍ...',
    launchAssessment: 'إطلاق التقييم',
    latestAssessment: 'آخر تقييم',
    overallScore: 'الدرجة الإجمالية',
    generateTasks: 'توليد المهام',
    identifiedRiskFactors: 'عوامل المخاطر المحددة',
    noSpecificRiskFactors: 'لم يتم تحديد عوامل مخاطر محددة',
    aiRecommendations: 'توصيات الذكاء الاصطناعي',
    noRecommendations: 'لا توجد توصيات متاحة',
    assessmentHistory: 'سجل التقييمات',
    number: 'الرقم',
    score: 'الدرجة',
    tasksLabel: 'المهام',
    generated: 'تم توليدها',
    noAssessments: 'لا توجد تقييمات للمخاطر. أطلق أول تحليل.',
    // Compliance Copilot page (EF2)
    ef2CopilotTitle: 'EF2: مساعد الامتثال',
    ef2CopilotSubtitle: 'مساعد ذكاء اصطناعي للامتثال ISO 9001, OSHA والمعايير الداخلية',
    chat: 'دردشة',
    knowledgeBase: 'قاعدة المعرفة',
    welcomeToCopilot: 'مرحباً بك في مساعد الامتثال',
    copilotDescription: 'اطرح أسئلتك حول معايير ISO 9001, ISO 14001, OSHA أو إجراءات الجودة الداخلية.',
    suggestion1: 'ما هي متطلبات ISO 9001 للتوثيق؟',
    suggestion2: 'كيفية إدارة عدم مطابقة رئيسية؟',
    suggestion3: 'إجراءات التدقيق الداخلي',
    sources: 'المصادر',
    askQuestion: 'اطرح سؤالك حول الامتثال...',
    searchKnowledgeBase: 'البحث في قاعدة المعرفة...',
    add: 'إضافة',
    emptyKnowledgeBase: 'قاعدة المعرفة فارغة',
    addStandardsProcedures: 'أضف المعايير والإجراءات وأدلة الامتثال.',
    consultations: 'استشارات',
    // Commonality Study page (EF3)
    ef3Subtitle: 'وكيل ReAct لتحديد الأنماط وتوصيات التحسين',
    newStudy: 'دراسة جديدة',
    studyTitle: 'عنوان الدراسة (اختياري)',
    defectAnalysis: 'تحليل العيوب',
    supplierComparison: 'مقارنة الموردين',
    processImprovement: 'تحسين العمليات',
    rootCauseAnalysis: 'تحليل السبب الجذري',
    reactAnalysisInProgress: 'تحليل ReAct جارٍ...',
    launchAnalysis: 'إطلاق التحليل',
    commonalityStudies: 'دراسات القواسم المشتركة',
    study: 'الدراسة',
    patterns: 'الأنماط',
    identified: 'محددة',
    approval: 'الموافقة',
    viewDetails: 'عرض التفاصيل',
    approve: 'موافقة',
    reject: 'رفض',
    noStudies: 'لا توجد دراسات. أطلق أول تحليل ReAct.',
    reactTrace: 'تتبع ReAct',
    step: 'الخطوة',
    thought: 'الفكرة',
    action: 'الإجراء',
    observation: 'الملاحظة',
    patternsIdentified: 'الأنماط المحددة',
    frequency: 'التكرار',
    confidence: 'الثقة',
    supplierInsights: 'رؤى الموردين',
    issues: 'المشاكل',
  },
  recipes: {
    title: 'الوصفات',
    subtitle: 'إدارة الوصفات والتركيبات والأوراق الفنية',
    recipeCards: 'بطاقات الوصفات',
    recipeName: 'اسم الوصفة',
    ingredients: 'المكونات',
    instructions: 'التعليمات',
    yield: 'الناتج',
    servings: 'الحصص',
    prepTime: 'وقت التحضير',
    cookTime: 'وقت الطهي',
    totalTime: 'الوقت الإجمالي',
    costPerServing: 'التكلفة لكل حصة',
    nutritionalInfo: 'المعلومات الغذائية',
    allergens: 'مسببات الحساسية',
    newRecipe: 'وصفة جديدة',
    totalRecipes: 'إجمالي الوصفات',
    activeRecipes: 'نشطة',
    draftRecipes: 'مسودات',
    categories: 'التصنيفات',
    searchRecipe: 'البحث عن وصفة...',
    allStatuses: 'جميع الحالات',
    allCategories: 'جميع التصنيفات',
    active: 'نشطة',
    draft: 'مسودة',
    archived: 'مؤرشفة',
    sellingPrice: 'سعر البيع',
    view: 'عرض',
    noRecipes: 'لا توجد وصفات',
    noRecipesDescription: 'ابدأ بإنشاء أول وصفة لك.',
    createRecipe: 'إنشاء وصفة',
    deleteRecipe: 'حذف الوصفة',
    deleteConfirmation: 'هل أنت متأكد من حذف',
    deleteWarning: 'هذا الإجراء لا يمكن التراجع عنه.',
    deleting: 'جاري الحذف...',
  },
  traceability: {
    title: 'التتبع',
    subtitle: 'الدفعات وامتثال HACCP',
    lots: 'الدفعات',
    lotNumber: 'رقم الدفعة',
    batchNumber: 'رقم الباتش',
    productionDate: 'تاريخ الإنتاج',
    expiryDate: 'تاريخ الانتهاء',
    haccp: 'HACCP',
    ccp: 'نقاط التحكم الحرجة',
    monitoring: 'المراقبة',
    corrective: 'الإجراءات التصحيحية',
    verification: 'التحقق',
    temperature: 'درجة الحرارة',
    humidity: 'الرطوبة',
  },
  payroll: {
    title: 'إدارة الرواتب',
    subtitle: 'إدارة الرواتب وكشوف المرتبات',
    periods: 'فترات الرواتب',
    payslips: 'كشوف المرتبات',
    employees: 'الموظفين',
    grossSalary: 'الراتب الإجمالي',
    netSalary: 'الراتب الصافي',
    deductions: 'الاستقطاعات',
    contributions: 'الاشتراكات',
    bonuses: 'المكافآت',
    overtime: 'العمل الإضافي',
    taxes: 'الضرائب',
    cnss: 'الضمان الاجتماعي',
    periodMonth: 'الشهر',
    periodYear: 'السنة',
    generate: 'إنشاء',
    validate: 'تصديق',
    process: 'معالجة',
  },
  settings: {
    title: 'الإعدادات',
    subtitle: 'تكوين المنصة',
    platform: 'إعدادات المنصة',
    modules: 'إدارة الوحدات',
    language: 'لغة المنصة',
    country: 'البلد',
    currency: 'العملة الافتراضية',
    timezone: 'المنطقة الزمنية',
    dateFormat: 'تنسيق التاريخ',
    numberFormat: 'تنسيق الأرقام',
    theme: 'السمة',
    darkMode: 'الوضع الداكن',
    lightMode: 'الوضع الفاتح',
    system: 'النظام',
    security: 'الأمان',
    backup: 'النسخ الاحتياطي',
    import: 'استيراد البيانات',
    export: 'تصدير البيانات',
    users: 'المستخدمين',
    roles: 'الأدوار',
    permissions: 'الصلاحيات',
    organization: 'المنظمة',
    companyInfo: 'معلومات الشركة',
    billing: 'الفواتير',
    subscription: 'الاشتراك',
    modulesList: 'قائمة الوحدات',
    enableModule: 'تفعيل الوحدة',
    disableModule: 'تعطيل الوحدة',
  },
  help: {
    title: 'مركز المساعدة',
    subtitle: 'التوثيق والدعم',
    gettingStarted: 'البدء',
    faq: 'الأسئلة الشائعة',
    moduleGuides: 'أدلة الوحدات',
    searchHelp: 'البحث في المساعدة',
    contactSupport: 'الاتصال بالدعم',
    documentation: 'التوثيق',
    tutorials: 'الدروس',
    videos: 'الفيديوهات',
    community: 'المجتمع',
  },
  ai: {
    title: 'الذكاء الاصطناعي',
    subtitle: 'ميزات الذكاء الاصطناعي المتقدمة',
    assistant: 'المساعد الذكي',
    predictions: 'التنبؤات',
    insights: 'الرؤى',
    automation: 'الأتمتة',
    askAnything: 'اسأل أي شيء...',
    generating: 'جاري الإنشاء...',
    suggestions: 'الاقتراحات',
  },
  languages: {
    fr: 'Français',
    en: 'English',
    ar: 'العربية',
  },
  footer: {
    allRightsReserved: 'جميع الحقوق محفوظة',
    documentation: 'التوثيق',
    support: 'الدعم',
  },
};

const translations: Record<Language, Translations> = { fr, en, ar };

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: 'ltr' | 'rtl';
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language') as Language;
    return saved && ['fr', 'ar', 'en'].includes(saved) ? saved : 'fr';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
    // Update HTML attributes for RTL support
    document.documentElement.lang = lang;
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
  };

  // Set initial direction on mount
  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
  }, [language]);

  // Translation function with nested key support (e.g., "profile.title")
  const t = (key: string): string => {
    const keys = key.split('.');
    let result: Translations | string = translations[language];

    for (const k of keys) {
      if (typeof result === 'object' && result !== null && k in result) {
        result = result[k];
      } else {
        // Fallback to French if key not found
        let fallback: Translations | string = translations.fr;
        for (const fk of keys) {
          if (typeof fallback === 'object' && fallback !== null && fk in fallback) {
            fallback = fallback[fk];
          } else {
            return key; // Return key if not found in fallback either
          }
        }
        return typeof fallback === 'string' ? fallback : key;
      }
    }

    return typeof result === 'string' ? result : key;
  };

  const dir = language === 'ar' ? 'rtl' : 'ltr';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
